### PR TITLE
couchstore: launch couch container from couchstore test

### LINKED ISSUE #244: couchstore: launch couch container from within couchstore_test
Instead of launching a couchdb instance outside of the sdk, launch it from couchstore_test

### PR DESCRIPTION
**Pull request by piedup**
I have also improved the create database with a retry to avoid instability in integration testing.

Resolves #244 

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/245)

### CODE REVIEW

**Comment by alexppxela** [comment]
Great feature, it should be great to have the same behavior for postgresql & rethinkdb

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[couchstore/api.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/245#-KzZ0CHO_ZdczLez2eka:-KzZ0CHPfBdk9oSip8CK:b19k0s9) ([raw file](https://github.com/stratumn/sdk/blob/db9b47d7f58fe46c8a302a9cef271931f441c036/couchstore/api.go#L31)):*
> ```Go
> 
> var (
> 	dbName string
> ```

It should be an CouchStore attribute to make api stateless

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/245#-:-KzZ0v7Bb0MBqb6x0mri:b3591u2)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[couchstore/api.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/245#-KzZ0CHO_ZdczLez2eka:-KzZ1yS50pr3f2jvyak9:b-m3ym05) ([raw file](https://github.com/stratumn/sdk/blob/db9b47d7f58fe46c8a302a9cef271931f441c036/couchstore/api.go#L31)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

It should be an CouchStore attribute to make api stateless
</blockquote></details>

I am just using this global variable to make it available to the retry function (defined in utils) as I can't pass additional parameters. So on create database this var is updated. Otherwise I can rewrite the retry function if you think this is not the best way to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/245)*

**Comment by piedup** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[couchstore/api.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/245#-KzZ0CHO_ZdczLez2eka:-KzcAcLHYZi-Ub7hGwAx:b64wrpd) ([raw file](https://github.com/stratumn/sdk/blob/735b38400d7dbba7159213103ea1918efadacec6/couchstore/api.go#L31)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

I am just using this global variable to make it available to the retry function (defined in utils) as I can't pass additional parameters. So on create database this var is updated. Otherwise I can rewrite the retry function if you think this is not the best way to it.
</blockquote></details>

As discussed I have used a closure to solve this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/245)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/245#-:-KzcAolOdFpxm3kyAek_:bnfp4nl)*

**Comment by piedup** [comment]
Had to rebase on top of master to integrate Simon Couchstore/TMPop tests. Otherwise code unchanged.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/245#-:-KzcHbystPv0nQddg54p:b-bvs8kj)*

**Pull request merged**
