### PR TITLE
agent-client-go: test cases and mock agent

### PR DESCRIPTION
**Pull request by simonvadee**
This is the second part of the agent-client (there are three in total).
It contains mainly two things : 
- a mock for the agent and its http server (I had to add an extra dependency to gorilla/mux for the router, because the one we are using in `storehttp` [does not support the agent's routes](https://github.com/julienschmidt/httprouter/issues/12))
- the testing package layout for the agent-client, It lives in its own sub-package because I felt it could be somehow shared with the agent tests but I did not figure out how exactly (I'm open to suggestions here)

Next PR will be actual implementation !

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/297)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[agent/process.go, line 30 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KsKW-lnhLR_cv3-Qc:-L0KsKW-lnhLR_cv3-Qd:b3wmq8w) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/process.go#L30)):*
> ```Go
> func (p Processes) FindProcess(name string) *Process {
> 	for _, process := range p {
> 		if process.Name == name {
> ```

nit: maybe we'll want to be case-insensitive here? I don't know if we're case-sensitive in the SDK

---

*[agent/agenttestcases/agenttestcases.go, line 36 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KssRAG84G68Y1D5-e:-L0KssRBMNZY03oqZFg-:b-dve83o) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/agenttestcases/agenttestcases.go#L36)):*
> ```Go
> 	f.Client, _ = f.NewClient(agentURL)
> 
> 	t.Run("TestCreateMap", f.TestCreateMap)
> ```

I would recommend putting all the CreateMap tests in a single test function (fixture) that will do multiple t.Run()
Have a look at what I did in the SDK store tests recently, it helps speed up the tests and organize them.
Same for the other test groups below.

---

*[agent/client/client_test.go, line 23 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KtfOG5P_TJ3kQs58K:-L0KtfOIUIFqMylSGOtd:bnmsof0) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/client/client_test.go#L23)):*
> ```Go
> 	seed := int64(time.Now().Nanosecond())
> 	fmt.Printf("using seed %d\n", seed)
> 	rand.Seed(seed)
> ```

Why do we need that? What random things are we doing that make it important to generate and output the seed?

---

*[agent/client/utils_test.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KtyMPoJdcEA3XQNPh:-L0KtyMPoJdcEA3XQNPi:bcv4wnv) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/client/utils_test.go#L38)):*
> ```Go
> 	bytes, err := json.Marshal(errorData)
> 	if err != nil {
> 		w.WriteHeader(500)
> ```

nit; we should use http status codes from the net package

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[agent/process.go, line 30 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KsKW-lnhLR_cv3-Qc:-L0Kxgn56ftf6RfQnnUX:bmr40hv) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/process.go#L30)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: maybe we'll want to be case-insensitive here? I don't know if we're case-sensitive in the SDK
</blockquote></details>

That's a valid point, but we're currently using case-sensitive comparisons in the SDK.

---

*[agent/agenttestcases/agenttestcases.go, line 36 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KssRAG84G68Y1D5-e:-L0KyMJLvH1x3-GQ05Fr:bsh0x0j) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/agenttestcases/agenttestcases.go#L36)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I would recommend putting all the CreateMap tests in a single test function (fixture) that will do multiple t.Run()
Have a look at what I did in the SDK store tests recently, it helps speed up the tests and organize them.
Same for the other test groups below.
</blockquote></details>

Thanks I'll do that :)

---

*[agent/client/client_test.go, line 23 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KtfOG5P_TJ3kQs58K:-L0KxXab0BbZSpTQBe3m:b-wyj5q6) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/client/client_test.go#L23)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Why do we need that? What random things are we doing that make it important to generate and output the seed?
</blockquote></details>

Actually you're right, we don't need tests to generate truely random hashes.

---

*[agent/client/utils_test.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KtyMPoJdcEA3XQNPh:-L0KxdcQYrE1NeGKCxGY:b-etnm8d) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/client/utils_test.go#L38)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit; we should use http status codes from the net package
</blockquote></details>

good point !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297)*

**Comment by simonvadee** [comment]
Review status: 7 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[agent/agenttestcases/agenttestcases.go, line 36 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KssRAG84G68Y1D5-e:-L0ON05nc1Jxw_ru4iP6:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/agenttestcases/agenttestcases.go#L36)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

Thanks I'll do that :)
</blockquote></details>

Done.

---

*[agent/client/client_test.go, line 23 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KtfOG5P_TJ3kQs58K:-L0OPFCULkiTmzi_27dd:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/client/client_test.go#L23)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

Actually you're right, we don't need tests to generate truely random hashes.
</blockquote></details>

Done.

---

*[agent/client/utils_test.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0KtyMPoJdcEA3XQNPh:-L0OPG_LX91eBQ7bT4oZ:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa0dfe2f164ff17a46bb36314fd5c0b726703ac3/agent/client/utils_test.go#L38)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

good point !
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297)*

**Comment by bejito** [comment]
*[agent/client/client_test.go, line 20 at r2](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0PNQ7upKjpPb6LvKHB:-L0PNQ7upKjpPb6LvKHC:b83iezq) ([raw file](https://github.com/stratumn/sdk/blob/d2f5a2415290a561a6f9160f70da321c788122dc/agent/client/client_test.go#L20)):*
> ```Go
> 
> func TestMain(m *testing.M) {
> 	seed := int64(time.Now().Nanosecond())
> ```

Where is this used ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297)*

**Comment by bejito** [comment]
:lgtm:

---

Reviewed 4 of 18 files at r1, 9 of 11 files at r2.
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297#-:-L0OiSNldam5ju5Zca0s:bnfp4nl)*

**Comment by simonvadee** [comment]
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[agent/client/client_test.go, line 20 at r2](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0PNQ7upKjpPb6LvKHB:-L0PPjEri4pLRJICVkJp:bap5fl9) ([raw file](https://github.com/stratumn/sdk/blob/d2f5a2415290a561a6f9160f70da321c788122dc/agent/client/client_test.go#L20)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

Where is this used ?
</blockquote></details>

right, it's no longer used 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297)*

**Comment by such** [comment]
Reviewed 7 of 18 files at r1, 9 of 11 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[agent/agenttestcases/agenttestcases.go, line 15 at r3](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0Pbx7tzjE1CsVaoyZG:-L0Pbx7tzjE1CsVaoyZH:b-7ilvfu) ([raw file](https://github.com/stratumn/sdk/blob/d9f9a60802388f7b1e90236567a73e0d3beebd7a/agent/agenttestcases/agenttestcases.go#L15)):*
> ```Go
> 
> // Factory wraps functions to mock an HTTP server for an agent and run
> // the  for the agent and its client
> ```

typo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297)*

**Comment by simonvadee** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[agent/agenttestcases/agenttestcases.go, line 15 at r3](https://reviewable.io:443/reviews/stratumn/sdk/297#-L0Pbx7tzjE1CsVaoyZG:-L0Pj7WiTplBcn3_5uoc:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/d9f9a60802388f7b1e90236567a73e0d3beebd7a/agent/agenttestcases/agenttestcases.go#L15)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/297#-:-L0Pl82p0a6j3X7WFloA:bnfp4nl)*

**Pull request merged**
