### PR TITLE
cs: RQL deserialisation of evidences

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/315)

### CODE REVIEW

**Comment by piedup** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[store/storetestcases/findsegments.go, line 333 at r1](https://reviewable.io:443/reviews/stratumn/sdk/315#-L1X_HXIVTV9PWgbb2bY:-L1X_HXJ3pVpcwDZ7IwJ:b-iax6ka) ([raw file](https://github.com/stratumn/sdk/blob/71adb415415a8b652888ce278a42591989ce6159/store/storetestcases/findsegments.go#L333)):*
> ```Go
> 		e4 := cs.Evidence{Backend: "bcbatch", Provider: "4", Proof: &evidences.BcBatchProof{}}
> 		e5 := cs.Evidence{Backend: "generic", Provider: "5"}
> 		evidences := []cs.Evidence{e1, e2, e3, e4, e5}
> ```

This is the same name as the evidences package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/315#-:-L1X_PHXrTp7ApoX6oIP:bnfp4nl)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cs/evidence.go, line 97 at r1](https://reviewable.io:443/reviews/stratumn/sdk/315#-L1XaF96e0tcpr3OoHkw:-L1XaF97q0rjsDCcO03A:b-2dzex3) ([raw file](https://github.com/stratumn/sdk/blob/71adb415415a8b652888ce278a42591989ce6159/cs/evidence.go#L97)):*
> ```Go
> }
> 
> // MarshalRQL serializes an Evidence into an JSON-formatted byteq array
> ```

nit: typo (byteq)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/315#-:-L1XahzVZDEVkz4UkUhZ:bnfp4nl)*

**Comment by simonvadee** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cs/evidence.go, line 97 at r1](https://reviewable.io:443/reviews/stratumn/sdk/315#-L1XaF96e0tcpr3OoHkw:-L1XlxeNkk7D5RPeMTMp:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/71adb415415a8b652888ce278a42591989ce6159/cs/evidence.go#L97)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: typo (byteq)?
</blockquote></details>

Done.

---

*[store/storetestcases/findsegments.go, line 333 at r1](https://reviewable.io:443/reviews/stratumn/sdk/315#-L1X_HXIVTV9PWgbb2bY:-L1XlyRVhVOiH9rak8Cg:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/71adb415415a8b652888ce278a42591989ce6159/store/storetestcases/findsegments.go#L333)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

This is the same name as the evidences package.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/315)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/315)*

**Pull request merged**
