### PR TITLE
store: SegmentFilter.LinkHashes to []string

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/295)

### CODE REVIEW

**Comment by conord33** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/295#-:-L0FyULNlBOTfk2OSkrY:bnfp4nl)*

**Comment by such** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[postgresstore/reader.go, line 95 at r1](https://reviewable.io:443/reviews/stratumn/sdk/295#-L0KC00PSNZaD5_SQcVZ:-L0KC00PSNZaD5_SQcV_:bet0jn6) ([raw file](https://github.com/stratumn/sdk/blob/785c033064830f29fd587d6afb7894e8fa58d98f/postgresstore/reader.go#L95)):*
> ```Go
> 			}
> 			linkHashes = append(linkHashes, linkHashBytes)
> 		}
> ```

I think you could have created a type for LinkHash lists and added this code as a function of that type. This would have prevented some duplication. What do you think?
It's only present twice but I think it would be a bit cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/295)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[postgresstore/reader.go, line 95 at r1](https://reviewable.io:443/reviews/stratumn/sdk/295#-L0KC00PSNZaD5_SQcVZ:-L0KD2k4EmVv26rvXl46:b-2h5v26) ([raw file](https://github.com/stratumn/sdk/blob/785c033064830f29fd587d6afb7894e8fa58d98f/postgresstore/reader.go#L95)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I think you could have created a type for LinkHash lists and added this code as a function of that type. This would have prevented some duplication. What do you think?
It's only present twice but I think it would be a bit cleaner.
</blockquote></details>

I was wondering about it and wasn't sure if it was worth it, but it would be cleaner indeed !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/295)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/295#-:-L0KFROI9LePq4T4HRvr:bnfp4nl)*

**Comment by simonvadee** [comment]
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[postgresstore/reader.go, line 95 at r1](https://reviewable.io:443/reviews/stratumn/sdk/295#-L0KC00PSNZaD5_SQcVZ:-L0KGc34JbDOH-FRFF7y:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/785c033064830f29fd587d6afb7894e8fa58d98f/postgresstore/reader.go#L95)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

I was wondering about it and wasn't sure if it was worth it, but it would be cleaner indeed !
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/295)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/295#-:-L0KIn8P7h2EjEagEd4S:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/295#-:-L0KJS7jrqPt8uyWkDHW:bnfp4nl)*

**Pull request merged**
