### PR TITLE
*: fix test_headers script and add missing license headers

### PR DESCRIPTION
**Pull request by such**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/331)

### CODE REVIEW

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 59 at r1](https://reviewable.io:443/reviews/stratumn/sdk/331#-L3cZyzEcnhfwyLbsU3S:-L3cZyzEcnhfwyLbsU3T:b-vff63m) ([raw file](https://github.com/stratumn/sdk/blob/9f8ce3a101818c41e8f09b55158ee60add34debc/Makefile#L59)):*
> ```Makefile
> ZIP_FILES=$(NIX_ZIP_FILES) $(WIN_ZIP_FILES)
> DOCKER_FILES=$(foreach command, $(COMMANDS), $(DIST_DIR)/$(command).Dockerfile)
> LICENSED_FILES=$(shell find . -name '*.go' | grep -v vendor | grep -v mock)
> ```

why do we exclude mock files?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/331#-:-L3c_6rmeNxVKfoqujCg:bnfp4nl)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 59 at r1](https://reviewable.io:443/reviews/stratumn/sdk/331#-L3cZyzEcnhfwyLbsU3S:-L3caNCJp1e-u0AaAHmy:b3aohv) ([raw file](https://github.com/stratumn/sdk/blob/9f8ce3a101818c41e8f09b55158ee60add34debc/Makefile#L59)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

why do we exclude mock files?
</blockquote></details>

Mockgen does not take the header of the source file into account. This would force us the modify manually the generated files...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/331)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/331#-:-L3caogb7NiGULGluS1z:bnfp4nl)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 3 of 29 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/331#-:-L3cbWSpjGByz4pqfTlL:bnfp4nl)*

**Pull request merged**
