### PR TITLE
Merge goprivate

### PR DESCRIPTION
**Pull request by such**
For now, I've kept the license that was originally in the private repository:

```
Unless otherwise noted, you may not use or distribute this software and/or any
of the source code without explicit written permission from Stratumn SAS.

If you have obtained a copy this software and/or any of the source code without
a license, please contact <hello@stratumn.com>.
```

We could also decide to use (A)GPL as discussed earlier. We really need to find a consensus and make a decision on that. Probably before merging.

Apart from that, this was pretty fun git foo:

Keep only the history of all files in a subdirectory and prefix the commit message with the directory name:
```
git filter-branch -f --subdirectory-filter cmd --msg-filter 'sed "1,/^/s/^/cmd: /"' -- --all
```

Move those files back to a directory:
```
git filter-branch -f --index-filter \
               'git ls-files -s | gsed "s-\t\"*-&cmd/-" |
                       GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
                               git update-index --index-info &&
                mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"' HEAD
```

And then some cherry picking...

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/266)

### CODE REVIEW

**Comment by alexppxela** [comment]
I think you forgot `merkle` library in apache license exception

---

Reviewed 8 of 97 files at r1.
Review status: 8 of 97 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Makefile, line 59 at r1](https://reviewable.io:443/reviews/stratumn/sdk/266#-L-BfhdxfScYmF9mq1a4:-L-Bfhdyayo1uoC6URNu:b3qjnky) ([raw file](https://github.com/stratumn/sdk/blob/dd8a45eab8285b814f99365424b535685b941e87/Makefile#L59)):*
> ```Makefile
> ZIP_FILES=$(NIX_ZIP_FILES) $(WIN_ZIP_FILES)
> DOCKER_FILES=$(foreach command, $(COMMANDS), $(DIST_DIR)/$(command).Dockerfile)
> LICENSED_FILES=$(shell find . -name '*.go' | grep -Ev "batchfossilizer|bcbatchfossilizer|blockchain|postgresstore|rethinkstore|btcfossilizer|dummybatchfossilizer|postgrestmpop|rethinktmpop")
> ```

You should keep vendor to be more performant (and maybe for the future)

---

*[README.md, line 22 at r1](https://reviewable.io:443/reviews/stratumn/sdk/266#-L-Bg8p1HKYMBt9YvVpN:-L-Bg8p1HKYMBt9YvVpO:b-vwfn4s) ([raw file](https://github.com/stratumn/sdk/blob/dd8a45eab8285b814f99365424b535685b941e87/README.md#L22)):*
> ```Markdown
> 
> You need Docker to be able to run the tests. The images `rethink:latest` and
> `postgres:latest` will be run automatically (and pulled from the docker hub if
> ```

and `couchstore:latest`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/266#-:-L-BgUbNvYaVZ6Xnt575:b5soql8)*

**Comment by t-bast** [comment]
I think it's ok if our merkle tree is apache licensed, isn't it?
I must admit I don't know about the licensing decision, otherwise :lgtm:

---

Reviewed 8 of 97 files at r1.
Review status: 13 of 97 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/266#-:-L-BhBfC4z1PYGXhGLpM:b3wzpad)*

**Comment by simonvadee** [comment]
*[README.md, line 22 at r1](https://reviewable.io:443/reviews/stratumn/sdk/266#-L-Bg8p1HKYMBt9YvVpN:-L-C7W3FHeVVgpjBqYuG:bbn6l1j) ([raw file](https://github.com/stratumn/sdk/blob/dd8a45eab8285b814f99365424b535685b941e87/README.md#L22)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

and `couchstore:latest`
</blockquote></details>

couchstore is not part of goprivate, but it will be worth adding when actually merging the README

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/266)*

**Comment by such** [comment]
since we'll use merkle in Apache packages, it should probably be Apache as well.

---

Review status: 12 of 129 files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 59 at r1](https://reviewable.io:443/reviews/stratumn/sdk/266#-L-BfhdxfScYmF9mq1a4:-L-CM8KSkXPTnK3xaXxR:b-l4jprq) ([raw file](https://github.com/stratumn/sdk/blob/dd8a45eab8285b814f99365424b535685b941e87/Makefile#L59)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

You should keep vendor to be more performant (and maybe for the future)
</blockquote></details>

right!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/266#-:-L-CLyFfL5fbHGGqYU7M:b84mxe1)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 13 of 43 files at r2, 1 of 1 files at r3.
Review status: 25 of 129 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/266#-:-L-CQ6xi_oNAKo4LM_5x:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: 25 of 129 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/266#-:-L-Cm3FxYsHXQeyx6XKD:bnfp4nl)*

**Pull request merged**
