### PR TITLE
validator, cs: add signature type and signature validator

### PR DESCRIPTION
**Pull request by simonvadee**
- link format is evolving : there is a new `Signatures` field 
```golang
type Link struct {
	State      map[string]interface{} `json:"state"`
	Meta       map[string]interface{} `json:"meta"`
	Signatures []*Signature           `json:"signatures"`
}
```

- a new boolean `signatures` can be added in in the validators : 
```json
"myprocess": [{
   "type": "init",
   "signatures": true,
   "schema": {...}
}, {
   "type": "someAction",
   "signatures": true
}]
```
If this boolean is set to true, signatures present in the link will be verified. If it's omitted, signatures won't be checked. This parameter may be used independently from the `schema` one.

NEXT PR : actual verification of signatures using the `go-jmespath` package to determine the payload and the `ed25519` signature algorithm.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/335)

### CODE REVIEW

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cs/cs_test.go, line 257 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AJAGkafCSvpKGQXo6:-L4AJAGlBlqsxeO3Wp63:b-a80e9o) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs_test.go#L257)):*
> ```Go
> }
> 
> func TestLinkValidate_emptySignatureType(t *testing.T) {
> ```

Is it possible to add a test with a valid link including a valid signature?

---

*[cs/signature.go, line 30 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AHSAxsQli74uT2yzT:-L4AHSAxsQli74uT2yzU:bcyt68z) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/signature.go#L30)):*
> "paylaod"
typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335#-:-L4AQDiVRniNMFm6uc0c:bnfp4nl)*

**Comment by such** [comment]
Great job!

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cs/cs.go, line 226 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AQizEZ483MQVpKv1b:-L4AQizEZ483MQVpKv1c:bisurv2) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs.go#L226)):*
> ```Go
> 
> // Validate checks for errors in a link.
> // It only validates the format of signatures, it does not verify their correctness
> ```

nit: we should try to end comments with a "." so that it looks better in godoc.

---

*[cs/cs.go, line 316 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4ARBvIqkKzv3gdJUGo:-L4ARBvIqkKzv3gdJUGp:b-uhava7) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs.go#L316)):*
> ```Go
> 			if sig.Type == "" {
> 				return errors.New("signature.Type cannot be empty")
> 			} else if _, err := hex.DecodeString(sig.PublicKey); err != nil || sig.PublicKey == "" {
> ```

do we go we hex encoding then? base64 might be a better choice in terms of concision...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335#-:-L4AVG6bA1NX6HljLxH-:bi0rogs)*

**Comment by t-bast** [comment]
Good job, you've made good progress on this feature ! I put a lot of comments but they are quite easy to fix :)

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[cs/cs.go, line 316 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4ARBvIqkKzv3gdJUGo:-L4A_BtAh06V5qgJ_pgh:b-7kynmv) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs.go#L316)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

do we go we hex encoding then? base64 might be a better choice in terms of concision...
</blockquote></details>

Agreed, for long []byte using base64 might be a better choice

---

*[cs/cs_test.go, line 259 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AUILxLRjKYNB-tNhA:-L4AUILyrMsmw9QIrh2n:b3n4xmx) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs_test.go#L259)):*
> ```Go
> func TestLinkValidate_emptySignatureType(t *testing.T) {
> 	l := cstesting.RandomLink()
> 	l.Signatures = append(l.Signatures, &cs.Signature{
> ```

I think it's worth adding a function in cstesting to generate signatures.
Something like SignLink(privateKey, path) where privateKey is a struct containing the private key bytes and its type.

---

*[cs/signature.go, line 24 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AVp3vwkWz-lZfhZxO:-L4AVp3w1rB3Vyf4XSrH:b-wzt3p5) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/signature.go#L24)):*
> ```Go
> 
> 	// PublicKey is the hex encoded public key that signed the payload
> 	PublicKey string `json:"publicKey"`
> ```

Why isn't it a []byte directly?
Same for signature below.

---

*[validator/configloader.go, line 64 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AX20wm2gOcKyAY79o:-L4AX20x8qbhGTNl_Rew:b-b2m665) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/configloader.go#L64)):*
> ```Go
> 			if val.Type == "" {
> 				return nil, ErrMissingLinkType
> 			} else if val.Signatures == nil && val.Schema == nil {
> ```

nit: you don't need the else since you return inside the previous if

---

*[validator/multivalidator_test.go, line 46 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AXf3s2LX4Z3nIMOBf:-L4AXf3s2LX4Z3nIMOBg:b6okuha) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/multivalidator_test.go#L46)):*
> ```Go
> 			},
> 		},
> 		SignatureConfigs: []*signatureValidatorConfig{
> ```

I don't think adding this adds anything relevant to that test right now since you're adding the same thing in each validator.
I think you should change this test to do two t.Run :
  * One with the previous contents of the test
  * Another one where you create validators with only signature validators inside it with different signatureValidatorConfig and verify that the hash ends up being different
What do you think?

---

*[validator/signature.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AZ6n3BdCYhyAK7hxf:-L4AZ6n45gAljxUIOEpz:b-880gb5) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/signature.go#L31)):*
> ```Go
> // validate links.
> type signatureValidatorConfig struct {
> 	validatorBaseConfig
> ```

Why isn't this a *validatorBaseConfig?

---

*[validator/signature.go, line 54 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AZh42ki9RJ6NIBY18:-L4AZh42ki9RJ6NIBY19:b-yrd1mq) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/signature.go#L54)):*
> ```Go
> 
> // check that the process and link type match the validators' attributes
> func (sv signatureValidator) shouldValidate(link *cs.Link) bool {
> ```

Why do you need this ? Its implementation can be reduced to just:
return sv.config.shouldValidate(link) 
so you could directly use it inline instead of a new method right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335#-:-L4A_Me5BHXXZkDoCWya:bdd5dwo)*

**Comment by simonvadee** [comment]
Review status: 10 of 18 files reviewed at latest revision, 10 unresolved discussions.

---

*[cs/cs.go, line 226 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AQizEZ483MQVpKv1b:-L4AiRO_K0PwXYvRo3eT:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs.go#L226)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: we should try to end comments with a "." so that it looks better in godoc.
</blockquote></details>

Done.

---

*[cs/cs.go, line 316 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4ARBvIqkKzv3gdJUGo:-L4AiV2QOYWq7TGNjjRf:bp919h9) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs.go#L316)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Agreed, for long []byte using base64 might be a better choice
</blockquote></details>

I followed the spec here, but I agree base64 is a better choice. Done.

---

*[cs/cs_test.go, line 257 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AJAGkafCSvpKGQXo6:-L4AucbXPyd7SWpGRnWB:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs_test.go#L257)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Is it possible to add a test with a valid link including a valid signature?
</blockquote></details>

Done.

---

*[cs/cs_test.go, line 259 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AUILxLRjKYNB-tNhA:-L4At853UdNDaiHoGT-p:b-7y6553) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs_test.go#L259)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I think it's worth adding a function in cstesting to generate signatures.
Something like SignLink(privateKey, path) where privateKey is a struct containing the private key bytes and its type.
</blockquote></details>

I added `cstesting.SignLink(link)` but since it's a test utility function, I don't really see the point in specifying the private key and json query. We can still add a `func (l *Link) Sign(privateKey, path)` later if we need it. Does this make sense ?

---

*[cs/signature.go, line 24 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AVp3vwkWz-lZfhZxO:-L4AjZ9f4dghgXGUIju6:b20jsed) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/signature.go#L24)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Why isn't it a []byte directly?
Same for signature below.
</blockquote></details>

Hmm , it's worth begin discussed but I think using strings in the chainscript make it more user friendly and easier to interface with external code (we'd have to work with Buffer in nodejs and Uint8Array in plain javascript, I'd rather use string and convert it to []byte in the sdk...). What do you think ? 

---

*[cs/signature.go, line 30 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AHSAxsQli74uT2yzT:-L4AjM19MVN7nr-n-Bzl:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/signature.go#L30)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

> "paylaod"
typo
</blockquote></details>

Done.

---

*[validator/configloader.go, line 64 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AX20wm2gOcKyAY79o:-L4Al2lf05yeQBVc-6xN:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/configloader.go#L64)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: you don't need the else since you return inside the previous if
</blockquote></details>

Done.

---

*[validator/multivalidator_test.go, line 46 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AXf3s2LX4Z3nIMOBf:-L4B7sellvbp_aB1MOdx:bl7tnra) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/multivalidator_test.go#L46)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I don't think adding this adds anything relevant to that test right now since you're adding the same thing in each validator.
I think you should change this test to do two t.Run :
  * One with the previous contents of the test
  * Another one where you create validators with only signature validators inside it with different signatureValidatorConfig and verify that the hash ends up being different
What do you think?
</blockquote></details>

good point, done.

---

*[validator/signature.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AZ6n3BdCYhyAK7hxf:-L4AlQ7G4VIg4WZ9ifEB:b-m24tqc) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/signature.go#L31)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Why isn't this a *validatorBaseConfig?
</blockquote></details>

no reason. Done.

---

*[validator/signature.go, line 54 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AZh42ki9RJ6NIBY18:-L4Alfb_-rPOeO-5y8ib:bo0k2o3) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/signature.go#L54)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Why do you need this ? Its implementation can be reduced to just:
return sv.config.shouldValidate(link) 
so you could directly use it inline instead of a new method right?
</blockquote></details>

You're right, I thought we'd need more conditional statements than just checking the link's action and process, but it seems we don't. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cs/cs_test.go, line 259 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AUILxLRjKYNB-tNhA:-L4B913t-l0vY0NplY3y:brxp9sd) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/cs_test.go#L259)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I added `cstesting.SignLink(link)` but since it's a test utility function, I don't really see the point in specifying the private key and json query. We can still add a `func (l *Link) Sign(privateKey, path)` later if we need it. Does this make sense ?
</blockquote></details>

Sounds good!

---

*[cs/signature.go, line 24 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AVp3vwkWz-lZfhZxO:-L4B9A2glW4x_O3Lpamw:b3nhpua) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/signature.go#L24)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

Hmm , it's worth begin discussed but I think using strings in the chainscript make it more user friendly and easier to interface with external code (we'd have to work with Buffer in nodejs and Uint8Array in plain javascript, I'd rather use string and convert it to []byte in the sdk...). What do you think ? 
</blockquote></details>

I think that now that we chose to use a base64 string, it is good (as you say it's more readable).
Can you update the comments to replace "hex" by "base64"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335#-:-L4BADKX7UyXuuJPScKe:bnfp4nl)*

**Comment by alexppxela** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[validator/signature.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AZ6n3BdCYhyAK7hxf:-L4B9saHKVHkuqWjpDJ7:b-tm3639) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/signature.go#L31)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

no reason. Done.
</blockquote></details>

For my culture, what is the interest to use pointer inheritance instead of embedded inheritance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[validator/signature.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AZ6n3BdCYhyAK7hxf:-L4BBSUIclbWPGp4BcOX:b-65sapp) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/signature.go#L31)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

For my culture, what is the interest to use pointer inheritance instead of embedded inheritance
</blockquote></details>

Maybe I got confused, the thing that was bothering me was the need for the explicit dereference in newSignatureValidatorConfig

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[validator/signature.go, line 31 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AZ6n3BdCYhyAK7hxf:-L4BBlvvVaIKhfQoIRYH:byj6pwr) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/validator/signature.go#L31)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Maybe I got confused, the thing that was bothering me was the need for the explicit dereference in newSignatureValidatorConfig
</blockquote></details>

Good summary of pros and cons: https://stackoverflow.com/questions/28501976/embedding-in-go-with-pointer-or-with-value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335)*

**Comment by simonvadee** [comment]
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[cs/signature.go, line 24 at r1](https://reviewable.io:443/reviews/stratumn/sdk/335#-L4AVp3vwkWz-lZfhZxO:-L4BCETlW4I4plQgWAXI:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/91f783a04ce86f0abef29897bd073ebc1a0c3fa3/cs/signature.go#L24)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I think that now that we chose to use a base64 string, it is good (as you say it's more readable).
Can you update the comments to replace "hex" by "base64"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335)*

**Comment by such** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335#-:-L4BFeR7jTUew22bvRf7:bnfp4nl)*

**Comment by such** [comment]
Reviewed 7 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/335)*

**Pull request merged**
