### PR TITLE
Agent client implementation

### PR DESCRIPTION
**Pull request by simonvadee**
The travis build fails with an  `internal compiler error` when compiling with `go-docker` and using `go:tip` (last `golang/go` commit on master). We should find a solution to correct this before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/299)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[agent/agenttestcases/findsegments.go, line 34 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0d9z5IFyAZI7qk1vIM:-L0d9z5IFyAZI7qk1vIN:bnatwa3) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/agenttestcases/findsegments.go#L34)):*
> ```Go
> func (f Factory) TestFindSegmentsTags(t *testing.T) {
> 	process, tag := "test", "tag"
> 	f.Client.CreateMap(process, nil, tag)
> ```

Add a segment without tag to check that it is not found.
This test does not reveal if find works wel

---

*[agent/agenttestcases/findsegments.go, line 34 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0e2KC85b6_7K-xeFUy:-L0e2KC85b6_7K-xeFUz:b9ivb2k) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/agenttestcases/findsegments.go#L34)):*
> ```Go
> func (f Factory) TestFindSegmentsTags(t *testing.T) {
> 	process, tag := "test", "tag"
> 	f.Client.CreateMap(process, nil, tag)
> ```

Why tag is not a slice?

---

*[agent/agenttestcases/findsegments.go, line 56 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0dAT3MQ6cAfLQOeOEO:-L0dAT3MQ6cAfLQOeOEP:b-y9meh4) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/agenttestcases/findsegments.go#L56)):*
> ```Go
> func (f Factory) TestFindSegmentsLinkHashes(t *testing.T) {
> 	process := "test"
> 	parent, _ := f.Client.CreateMap(process, nil, "test")
> ```

Same as below

---

*[agent/client/client.go, line 89 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0dzDkCens0MmLDEcnf:-L0dzDkCens0MmLDEcng:bp98ngx) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/client/client.go#L89)):*
> impelmenting
nit: typo

---

*[agent/client/client.go, line 232 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0e1g-MqyZsZdbvB-kX:-L0e1g-MqyZsZdbvB-kY:b-la7sid) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/client/client.go#L232)):*
> ```Go
> 	decoder := json.NewDecoder(resp.Body)
> 	seg := cs.Segment{}
> 	if err := decoder.Decode(&seg); err != nil {
> ```

indigo-js preloads refs segments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[agent/agenttestcases/findsegments.go, line 34 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0e2KC85b6_7K-xeFUy:-L0eHTigXLnksApwUXZo:b-nxbkpx) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/agenttestcases/findsegments.go#L34)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why tag is not a slice?
</blockquote></details>

Because `CreateMap`and `CreateLink` take varargs and not a list (it's the same in agent-client-js)

---

*[agent/agenttestcases/findsegments.go, line 34 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0d9z5IFyAZI7qk1vIM:-L0eI7TsdV0Sx4jfTz-k:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/agenttestcases/findsegments.go#L34)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Add a segment without tag to check that it is not found.
This test does not reveal if find works wel
</blockquote></details>

Done.

---

*[agent/agenttestcases/findsegments.go, line 56 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0dAT3MQ6cAfLQOeOEO:-L0eHvRpqpXmxwkhJ2bS:b-ya81ng) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/agenttestcases/findsegments.go#L56)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Same as below
</blockquote></details>

Same as above

---

*[agent/client/client.go, line 89 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0dzDkCens0MmLDEcnf:-L0eI6KB-UN9eUkpOkFg:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/client/client.go#L89)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

> impelmenting
nit: typo
</blockquote></details>

Done.

---

*[agent/client/client.go, line 232 at r2](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0e1g-MqyZsZdbvB-kX:-L0eKUIknFA1TwQKXdjI:b1si21p) ([raw file](https://github.com/stratumn/sdk/blob/a328d8060ee5f0069371a05f31960169216c87aa/agent/client/client.go#L232)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

indigo-js preloads refs segments
</blockquote></details>

this is done on the agent side

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299)*

**Comment by such** [comment]
Impressive job! Thanks!

---

Review status: 9 of 13 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[agent/agenttestcases/createlink.go, line 32 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nvqTJuIsnzB-SadMr:-L0nvqTK6Nzh8S3JOvsb:b-vlclfk) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createlink.go#L32)):*
> ```Go
> 	ref := client.SegmentRef{Process: "other", LinkHash: testutil.RandomHash()}
> 	refs := make([]client.SegmentRef, 0)
> 	refs = append(refs, ref)
> ```

you could write `refs := [1]SegmentRef{{Process: "other", LinkHash: testutil.RandomHash()}}` I think

---

*[agent/agenttestcases/createlink.go, line 50 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nwYMQoFYsP5kL5Db-:-L0nwYMQoFYsP5kL5Db0:bb7i16w) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createlink.go#L50)):*
> ```Go
> 	ref := client.SegmentRef{Process: "wrong"}
> 	refs := make([]client.SegmentRef, 0)
> 	refs = append(refs, ref)
> ```

idem

---

*[agent/agenttestcases/createlink.go, line 80 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nwm85AvcDP8BmC8bq:-L0nwm85AvcDP8BmC8br:bzf2d5d) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createlink.go#L80)):*
> ```Go
> func (f Factory) TestCreateLinkHandlesWrongAction(t *testing.T) {
> 	process, action := "test", "wrong"
> 	parent, err := f.Client.CreateMap(process, nil, "test")
> ```

If we don't plan on check this `err` it should not be declared

---

*[agent/agenttestcases/createmap.go, line 26 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nx-p0Vhf9TH-fZJgs:-L0nx-p0Vhf9TH-fZJgt:byr4ffv) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createmap.go#L26)):*
> ```Go
> 	ref := client.SegmentRef{Process: "other", LinkHash: testutil.RandomHash()}
> 	refs := make([]client.SegmentRef, 0)
> 	refs = append(refs, ref)
> ```

see above

---

*[agent/agenttestcases/createmap.go, line 43 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nx49l-dX6E19ofZwn:-L0nx49l-dX6E19ofZwo:bb7i16w) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createmap.go#L43)):*
> ```Go
> 	ref := client.SegmentRef{Process: "wrong"}
> 	refs := make([]client.SegmentRef, 0)
> 	refs = append(refs, ref)
> ```

idem

---

*[agent/agenttestcases/findsegments.go, line 99 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nyAEN-ifTs1k6lkKL:-L0nyAEN-ifTs1k6lkKM:b5detci) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/findsegments.go#L99)):*
> ```Go
> 	created := 10
> 	expected := 0
> 	for i := 0; i != created; i++ {
> ```

nit: we usually write loops with `<` instead of `!=` in the codebase...

---

*[agent/agenttestcases/findsegments.go, line 123 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nzb8oHCuen_HyO6z1:-L0nzb8oHCuen_HyO6z2:b-hn5ovg) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/findsegments.go#L123)):*
> ```Go
> 	for i := 0; i != created; i++ {
> 		f.Client.CreateMap(process, nil, "test")
> 	}
> ```

I think the creation could be factorized with the previous test and we could use test fixtures.

---

*[agent/client/client.go, line 76 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o-Z_4YWb4cQdZQj8-:-L0o-Z_4YWb4cQdZQj80:b-dwyfaz) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L76)):*
> ```Go
> 
> // CreateLink sends a CreateLink request to the agent and returns
> // the newly created segment
> ```

nit: these comments need to end with `.` (looks better in godoc)

---

*[agent/client/client.go, line 77 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o-EC-t2YTTcAdF6-r:-L0o-EC-t2YTTcAdF6-s:bqvqo4x) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L77)):*
> ```Go
> // CreateLink sends a CreateLink request to the agent and returns
> // the newly created segment
> func (a *agentClient) CreateLink(process string, linkHash *types.Bytes32, action string, refs []SegmentRef, args ...string) (*cs.Segment, error) {
> ```

I thought we had decided to keep calling it `CreateSegment`?

---

*[agent/client/client.go, line 89 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o-O8ZZRyZbKh_fQIG:-L0o-O8ZZRyZbKh_fQIH:b-fpb8qk) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L89)):*
> ```Go
> 	decoder := json.NewDecoder(resp.Body)
> 	seg := cs.Segment{}
> 	// TODO: could be improved by implementing UnnmarshalJSON on cs.Segment
> ```

nit: I think it'd be better to create an Issue and remove this TODO

---

*[agent/client/client.go, line 201 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o0KjihRHfcUzTwA0E:-L0o0KjihRHfcUzTwA0F:b-2h16ny) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L201)):*
> ```Go
> 	process := processes.FindProcess(name)
> 	if process == nil {
> 		return nil, errors.New("Not Found")
> ```

I guess this kind of strings could be constants... What do you think?

---

*[agent/client/client.go, line 269 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o1FwtmkTmeq_Fv9Kp:-L0o1FwtmkTmeq_Fv9Kq:b-wvvygt) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L269)):*
> ```Go
> 			return nil, err
> 		}
> 		endpoint += "?" + queryParams.Encode()
> ```

I find it a bit odd that you have to write it like that.

I feel like you should do:
`url.RawQuery = queryParams.Encode()`

What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299#-:-L0o1mfbIQXaqK7NHs65:b8ci0ym)*

**Comment by simonvadee** [comment]
Review status: 9 of 13 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[agent/agenttestcases/createlink.go, line 32 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nvqTJuIsnzB-SadMr:-L0oAS2YNhcu86QhpIZX:b8tyci4) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createlink.go#L32)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

you could write `refs := [1]SegmentRef{{Process: "other", LinkHash: testutil.RandomHash()}}` I think
</blockquote></details>

It works with `[]` instead of `[1]` ! thanks.
Done.

---

*[agent/agenttestcases/createlink.go, line 50 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nwYMQoFYsP5kL5Db-:-L0oB4V5WmlIqEYqIgUJ:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createlink.go#L50)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

idem
</blockquote></details>

Done.

---

*[agent/agenttestcases/createlink.go, line 80 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nwm85AvcDP8BmC8bq:-L0oB2uzpAfKcmQJ2cST:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createlink.go#L80)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

If we don't plan on check this `err` it should not be declared
</blockquote></details>

Done.

---

*[agent/agenttestcases/createmap.go, line 26 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nx-p0Vhf9TH-fZJgs:-L0oB8EOy7utjOvZBpvO:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createmap.go#L26)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[agent/agenttestcases/createmap.go, line 43 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nx49l-dX6E19ofZwn:-L0oB9_1SICI6kEGgbts:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/createmap.go#L43)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

idem
</blockquote></details>

Done.

---

*[agent/agenttestcases/findsegments.go, line 99 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nyAEN-ifTs1k6lkKL:-L0oBQ8nmMgVVAt5E03V:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/findsegments.go#L99)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: we usually write loops with `<` instead of `!=` in the codebase...
</blockquote></details>

Done.

---

*[agent/agenttestcases/findsegments.go, line 123 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0nzb8oHCuen_HyO6z1:-L0oILoidk2MVJJpd5tN:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/agenttestcases/findsegments.go#L123)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I think the creation could be factorized with the previous test and we could use test fixtures.
</blockquote></details>

Done.

---

*[agent/client/client.go, line 76 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o-Z_4YWb4cQdZQj8-:-L0oE78Tt6G6bifcV6WL:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L76)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: these comments need to end with `.` (looks better in godoc)
</blockquote></details>

Done.

---

*[agent/client/client.go, line 77 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o-EC-t2YTTcAdF6-r:-L0oEF0JxLUv_LYH5OKw:b-u8z4bc) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L77)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I thought we had decided to keep calling it `CreateSegment`?
</blockquote></details>

The discussion we had was about the agent's API (replace `/segments` by `/links`) but you're right, it should be consistent with the API.
Done.

---

*[agent/client/client.go, line 89 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o-O8ZZRyZbKh_fQIG:-L0oEb9zT40iyQzxkhjO:btnwvds) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L89)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: I think it'd be better to create an Issue and remove this TODO
</blockquote></details>

Agreed !
Done.

---

*[agent/client/client.go, line 201 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o0KjihRHfcUzTwA0E:-L0oHg6i7i9rIqmCaGKj:b-e1ei5a) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L201)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I guess this kind of strings could be constants... What do you think?
</blockquote></details>

Agreed, error messages are a mess right now... it's coming in the next commit

---

*[agent/client/client.go, line 269 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o1FwtmkTmeq_Fv9Kp:-L0oNYgnopNmj7Sj9VE8:bw2x5p8) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L269)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I find it a bit odd that you have to write it like that.

I feel like you should do:
`url.RawQuery = queryParams.Encode()`

What do you think?
</blockquote></details>

I wasn't aware of the usage of `RawQuery`, but it's way better indeed.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r1, 13 of 13 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299#-:-L0oYvGmFSeAHHofILRQ:bnfp4nl)*

**Comment by simonvadee** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[agent/client/client.go, line 201 at r4](https://reviewable.io:443/reviews/stratumn/sdk/299#-L0o0KjihRHfcUzTwA0E:-L0og1mzVTyjdzZZHk_A:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/aa69afd3a17f83ad3f54f004e6c8576501fdc71d/agent/client/client.go#L201)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

Agreed, error messages are a mess right now... it's coming in the next commit
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299#-:-L0p2KNy5VHDV-8D1MNm:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/299#-:-L0tzRbUTsmU4SN8OU1x:bnfp4nl)*

**Pull request merged**
