### PR TITLE
cmd: update version

### PR DESCRIPTION
**Pull request by t-bast**
Since we're getting close to the release, I'm updating the version displayed by all our cmds.
I also updated the changelog with what I could find in the branch's history, let me know if I missed something important.
I think we only need to update the generators now, and do a bit of work on agent-ui to be ready to release.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/300)

### CODE REVIEW

**Comment by t-bast** [comment]
Let me know if you think it makes sense to merge this PR only once we've done the generators work and created a 0.2.0 release.

**Comment by such** [comment]
actually I think the version is already automatically overriden by `make`...

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/300#-:-L0ep2Vm2Rnoxl4ldZj7:b-jl43v4)*

**Comment by such** [comment]
Review status: 0 of 37 files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGE_LOG.md, line 3 at r1](https://reviewable.io:443/reviews/stratumn/sdk/300#-L0epsteNYLpXw8T3jTY:-L0epsteNYLpXw8T3jTZ:b5ck0ol) ([raw file](https://github.com/stratumn/sdk/blob/fe3abc30616f7f7fc567b741cdf1a91d30021e3e/CHANGE_LOG.md#L3)):*
> ```Markdown
> ## Change log
> 
> ### 0.2.0
> ```

we should probably mention it's BREAKING...

---

*[CHANGE_LOG.md, line 13 at r1](https://reviewable.io:443/reviews/stratumn/sdk/300#-L0eppraKBkqLxLNcOoU:-L0eppraKBkqLxLNcOoV:b-tjs1ok) ([raw file](https://github.com/stratumn/sdk/blob/fe3abc30616f7f7fc567b741cdf1a91d30021e3e/CHANGE_LOG.md#L13)):*
> ```Markdown
> * Refactored internal types to operate as much as possible on Links
> * Refactored types for more consistency
> * A Segment can now references existing Segments (even from other processes / maps)
> ```

typo: reference

---

*[CHANGE_LOG.md, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/300#-L0eplI0z2VRCUueKbs9:-L0eplI0z2VRCUueKbsA:b-ugmbnj) ([raw file](https://github.com/stratumn/sdk/blob/fe3abc30616f7f7fc567b741cdf1a91d30021e3e/CHANGE_LOG.md#L15)):*
> ```Markdown
> * A Segment can now references existing Segments (even from other processes / maps)
> * Added new store implementations (Rethink, CouchDB, PostgreSQL)
> * Added fossilizers implementations (BTCFossilizer, BatchFossilizer, DummyFossilizer)
> ```

nit: dummy fossilizer was already there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/300)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 37 of 37 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGE_LOG.md, line 6 at r2](https://reviewable.io:443/reviews/stratumn/sdk/300#-L0j223EuGzKyjrkpAKb:-L0j223EuGzKyjrkpAKc:b2nz68m) ([raw file](https://github.com/stratumn/sdk/blob/f46a0c44db7e634036ffc90e2e905e917fb1bb96/CHANGE_LOG.md#L6)):*
> ```Markdown
> 
> * Updated to Tendermint 0.13.0
> * Updated license
> ```

License was already apache2.0?
You mentioned below new stores & fossilizers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/300#-:-L0j2ns5rW4_86enPwmf:bnfp4nl)*

**Comment by t-bast** [comment]
Review status: 36 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGE_LOG.md, line 6 at r2](https://reviewable.io:443/reviews/stratumn/sdk/300#-L0j223EuGzKyjrkpAKb:-L0j4B36SxzFKn7q0jPk:b-x1f5u) ([raw file](https://github.com/stratumn/sdk/blob/f46a0c44db7e634036ffc90e2e905e917fb1bb96/CHANGE_LOG.md#L6)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

License was already apache2.0?
You mentioned below new stores & fossilizers
</blockquote></details>

Thanks, removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/300)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/300#-:-L0j9gdmNuCLo5e5s9uO:bnfp4nl)*

**Pull request merged**
