### PR TITLE
store: rework store events

### PR DESCRIPTION
**Pull request by t-bast**
It's more useful if it allows batching of saved links and maps evidences to a link hash.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/280)

### CODE REVIEW

**Comment by piedup** [comment]
Reviewed 15 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[store/store_test.go, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/280#-L-pMo8u5a3eVpsuuMNK:-L-pMo8u5a3eVpsuuMNL:btesbb2) ([raw file](https://github.com/stratumn/sdk/blob/aa74f8b983f4eb80bf85b0286fb3e8168b0c0229/store/store_test.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package store_test
> ```

Is there a particular reason for putting these tests in a different package than the store package?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280)*

**Comment by piedup** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/store_test.go, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/280#-L-pMo8u5a3eVpsuuMNK:-L-pNWOfs4TL_jSRoosu:b-81o1eb) ([raw file](https://github.com/stratumn/sdk/blob/aa74f8b983f4eb80bf85b0286fb3e8168b0c0229/store/store_test.go#L15)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Is there a particular reason for putting these tests in a different package than the store package?
</blockquote></details>

It's simply that this way the code isn't in the production executable...I think go recommends this as a best practice if you're doing black-box testing (which we should be doing).
See https://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-with-the-go-language

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/store_test.go, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/280#-L-pMo8u5a3eVpsuuMNK:-L-pRJK-6944_ZSvmEou:bg7xw7x) ([raw file](https://github.com/stratumn/sdk/blob/aa74f8b983f4eb80bf85b0286fb3e8168b0c0229/store/store_test.go#L15)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

It's simply that this way the code isn't in the production executable...I think go recommends this as a best practice if you're doing black-box testing (which we should be doing).
See https://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-with-the-go-language
</blockquote></details>

It makes sense indeed for blackbox testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280)*

**Comment by piedup** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280#-:-L-pRRmf2y6lKXTi2tvB:bnfp4nl)*

**Comment by bejito** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280#-:-L-pRe2BV7mWjW4-VENP:bg7igk9)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/store_test.go, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/280#-L-pMo8u5a3eVpsuuMNK:-L-pRtounQ9Jta1KOPbp:b-5d6u5x) ([raw file](https://github.com/stratumn/sdk/blob/aa74f8b983f4eb80bf85b0286fb3e8168b0c0229/store/store_test.go#L15)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

It makes sense indeed for blackbox testing.
</blockquote></details>

And this way you don't have an unnecessarily big executable because the prod executable will only contain the real code, not the test code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280)*

**Comment by alexppxela** [comment]
*[store/store_test.go, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/280#-L-pMo8u5a3eVpsuuMNK:-L-pX8rYDgvY3fE97P6e:bszqjrj) ([raw file](https://github.com/stratumn/sdk/blob/aa74f8b983f4eb80bf85b0286fb3e8168b0c0229/store/store_test.go#L15)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

And this way you don't have an unnecessarily big executable because the prod executable will only contain the real code, not the test code
</blockquote></details>

Tests are not included in executable.
If you don't need to access to unexported symbol, your method is good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/280)*

**Pull request merged**
