### PR TITLE
couchstore: initial commit

### LINKED ISSUE #213: couchbasestore: create a couchbasestore
Most of the work has already been done with the implementation of the `fabricstore`. The code could be extracted into a specific implementation.

### PR DESCRIPTION
**Pull request by piedup**
Resolves #213

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/234)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[couchstore/api.go, line 28 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-furPNacuNoVeB5wY:-Kz-furPNacuNoVeB5wZ:b-m9hxu2) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L28)):*
> ```Go
> 	"github.com/stratumn/sdk/cs"
> 	"github.com/stratumn/sdk/types"
> )
> ```

Is there a reason why you're not using a couchdb go package to interact with the db? It would allow us to get rid of most of the boilerplate code...is it because of licensing issues?

---

*[couchstore/api.go, line 64 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-gH4ISLMY5Jy63wTU:-Kz-gH4ISLMY5Jy63wTV:b7erym1) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L64)):*
> ```Go
> 	Process string `json:"process,omitempty"`
> 
> 	// Value specific
> ```

This comment (and the others) aren't really useful...do you mean that this field will only be populated when the document is a value document?

---

*[couchstore/api.go, line 263 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-hQ6FsKAimYC5mds7:-Kz-hQ6FsKAimYC5mds8:btfwznt) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L263)):*
> ```Go
> }
> 
> func (c *CouchStore) delete(path string) ([]byte, *CouchResponseStatus, error) {
> ```

This method does exactly the same thing as the one above (put). The only things changing are the data and the http method.
Maybe it's worth extracting that to a function DoHttpRequest(httpMethod, data)?

---

*[couchstore/couchstore.go, line 72 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-hzI2aLup-dvWFjQW:-Kz-hzI2aLup-dvWFjQX:b-q7v9ua) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L72)):*
> ```Go
> 	if resp.StatusCode != 200 {
> 		fmt.Println(resp)
> 		return nil, errors.New("CouchDB dit not return 200")
> ```

nit: typo: 'did'
It's probably interesting to also include the status code in the error message.

---

*[couchstore/couchstore.go, line 167 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-iKBWsFdkiGExzxJk:-Kz-iKBWsFdkiGExzxJl:bpzlrcw) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L167)):*
> ```Go
> 		segments = append(segments, couchFindResponse.Docs[i].Segment)
> 	}
> 	sort.Sort(segments)
> ```

why do you need to sort those?

---

*[couchstore/queries.go, line 76 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-jLkI5yvk6_V3XDw2:-Kz-jLkI5yvk6_V3XDw3:by2jstw) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/queries.go#L76)):*
> ```Go
> 		segmentSelector.MapIds = &MapIdsIn{filter.MapIDs}
> 	} else {
> 		segmentSelector.Tags = nil
> ```

did you mean MapIds here?
Some unit tests will probably be useful to catch that :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[couchstore/api.go, line 28 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-furPNacuNoVeB5wY:-Kz-luRvv3KubWXXXlEE:b-84odod) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L28)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Is there a reason why you're not using a couchdb go package to interact with the db? It would allow us to get rid of most of the boilerplate code...is it because of licensing issues?
</blockquote></details>

I didn't find any "official" go package for couchdb. Given there is only a few api calls I thought it made sense to write some boilerplate.

---

*[couchstore/api.go, line 64 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-gH4ISLMY5Jy63wTU:-Kz-m5l2HPvfuXoJS8Z4:b-rapxfp) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L64)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

This comment (and the others) aren't really useful...do you mean that this field will only be populated when the document is a value document?
</blockquote></details>

Yes, depending on what is stored on the DB (segment, map or value) the document contains different fields. I can remove this but I thought this would make it more clear in case we want to add something later on.

---

*[couchstore/couchstore.go, line 167 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-iKBWsFdkiGExzxJk:-Kz-mSHHf7442Vvd6eUr:b-e5mabi) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L167)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

why do you need to sort those?
</blockquote></details>

Segments need to be sorted so that agent can easily build the map. filestore also sorts the segments after a find.

---

*[couchstore/queries.go, line 76 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-jLkI5yvk6_V3XDw2:-Kz-mfHo0i-NAuPZV-CP:b-belkhh) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/queries.go#L76)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

did you mean MapIds here?
Some unit tests will probably be useful to catch that :)
</blockquote></details>

MapIdsIn is used to build the couched query.
All unit tests are common for all stores they are in store/storetestcases.go, all test run successfully on couchstore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[couchstore/api.go, line 28 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-furPNacuNoVeB5wY:-Kz-ovpjzUc3IZxcKYzh:bkk5qh1) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L28)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

I didn't find any "official" go package for couchdb. Given there is only a few api calls I thought it made sense to write some boilerplate.
</blockquote></details>

Also part of this code can be reused in the fabric store implementation of couchdb which requires to write queries rather than use an existing implementation of couchdb. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by such** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-Kz-rALUzs9ps1UN_ZfA:bs889be) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
> ```YAML
>   - dep ensure
> script:
>   - docker run -p 5984:5984 -d couchdb
> ```

This could probably be documented in the README as well

---

*[couchstore/couchstore.go, line 167 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-iKBWsFdkiGExzxJk:-Kz-q3MNx8K7lOQLTmLw:bunmoz8) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L167)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Segments need to be sorted so that agent can easily build the map. filestore also sorts the segments after a find.
</blockquote></details>

I just checked and it's implicitly part of the contract. We use the link.meta.priority field for sorting and this is the very specification of this field.

---

*[couchstore/queries.go, line 76 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-jLkI5yvk6_V3XDw2:-Kz-scetgUXjazJhB71_:ba4jfe3) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/queries.go#L76)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

MapIdsIn is used to build the couched query.
All unit tests are common for all stores they are in store/storetestcases.go, all test run successfully on couchstore.
</blockquote></details>

I'm with @t-bast here, I don't really get this line of code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[couchstore/queries.go, line 76 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-jLkI5yvk6_V3XDw2:-Kz004ocHALCEkwtJRE-:bdu33ei) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/queries.go#L76)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I'm with @t-bast here, I don't really get this line of code.
</blockquote></details>

Actually you are right. I wasn't looking at the right line. I'll change that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-Kz08I4ufzMEAnzFqrQl:b-gvbuwv) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

This could probably be documented in the README as well
</blockquote></details>

Should we have a README for each store?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by t-bast** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-Kz2n12851leyAQXJl5L:b-dpd3tz) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Should we have a README for each store?
</blockquote></details>

It might be a good idea indeed, and we could argue there for the benefits and drawbacks of each store (and maybe later post some perf results)

---

*[couchstore/api.go, line 28 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-furPNacuNoVeB5wY:-Kz2nHaEayNRQBLe_bdA:b-bcu2c6) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L28)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Also part of this code can be reused in the fabric store implementation of couchdb which requires to write queries rather than use an existing implementation of couchdb. 
</blockquote></details>

Sounds good then !

---

*[couchstore/api.go, line 64 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-gH4ISLMY5Jy63wTU:-Kz2nL1qyufRiVU7uHtj:b-1dh4q7) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L64)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Yes, depending on what is stored on the DB (segment, map or value) the document contains different fields. I can remove this but I thought this would make it more clear in case we want to add something later on.
</blockquote></details>

Then do you mind putting a more explicit comment, something like "This field is only populated when the document contains a value"?

---

*[couchstore/couchstore.go, line 167 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-iKBWsFdkiGExzxJk:-Kz2nvfYlJ7EYRWWNLxm:bbzjkgx) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L167)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I just checked and it's implicitly part of the contract. We use the link.meta.priority field for sorting and this is the very specification of this field.
</blockquote></details>

That's interesting. I think we should either make it well documented or sort at the agent level don't you think? If we do it at the agent level we only need to do it in one place instead of in every store (but that change is probably for another pull request)

---

*[couchstore/couchstore.go, line 72 at r2](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz2nhWuaJc5_mhoDpZx:-Kz2nhWvFwiLCL8etUbP:b-yd9ank) ([raw file](https://github.com/stratumn/sdk/blob/005fc4792355073553323f3cc5c4b4306d31b1d3/couchstore/couchstore.go#L72)):*
> ```Go
> 	if resp.StatusCode != 200 {
> 		fmt.Println(resp)
> 		return nil, fmt.Errorf(fmt.Sprintf("CouchDB returned status code %v, expected 200", resp.StatusCode))
> ```

nit: Errorf already takes a format string as input, no need for the inner fmt.Sprintf, I think you can directly write:
fmt.Errorf("CouchDB returned status code %v, expected 200", resp.StatusCode)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-Kz32Ei4d8K2-I_pKwKl:bejvwp1) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

It might be a good idea indeed, and we could argue there for the benefits and drawbacks of each store (and maybe later post some perf results)
</blockquote></details>

It might be a good idea but that's not what I meant. I meant that we need to document in the development section how to run the tests.

---

*[couchstore/couchstore.go, line 167 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-iKBWsFdkiGExzxJk:-Kz32a3nV73uDrISZH0h:bmld86v) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L167)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

That's interesting. I think we should either make it well documented or sort at the agent level don't you think? If we do it at the agent level we only need to do it in one place instead of in every store (but that change is probably for another pull request)
</blockquote></details>

We can't do it at the agent level because pagination...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-Kz36Yo1jERpQ96HOB84:byue42b) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

It might be a good idea but that's not what I meant. I meant that we need to document in the development section how to run the tests.
</blockquote></details>

Do you think it is worth launching the couched docker container in the TestMain, run the tests and bring down the container? I guess it could be done via a go docker client.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-Kz37ifJeDlANO6umZpx:b-h1k0rh) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Do you think it is worth launching the couched docker container in the TestMain, run the tests and bring down the container? I guess it could be done via a go docker client.
</blockquote></details>

That's a good idea. The only thing is that it makes docker a mandatory requirement to develop on the SDK but I guess it's fine. @stephan83 what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[couchstore/couchstore.go, line 167 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-iKBWsFdkiGExzxJk:-Kz37zwN_qsXiewcNxYn:b-q4cegc) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L167)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

We can't do it at the agent level because pagination...
</blockquote></details>

Ah good point, then it makes sense that the store has to do it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-Kz38LyLi_RoQk_yWZXS:bd4jyal) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

That's a good idea. The only thing is that it makes docker a mandatory requirement to develop on the SDK but I guess it's fine. @stephan83 what do you think?
</blockquote></details>

Otherwise what I have done in the fabricstore is use a flag -integration. When passing this flag to go test it will run all the integration tests such as couchdb. Travis could run -integration on deployment, but default behaviour would be to run without the -integration flag. The only downside is that you have to add `integration = flag.String("integration", false, "Run integration tests")` in all test files of the sdk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by alexppxela** [comment]
Reviewed 3 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[couchstore/batch.go, line 42 at r2](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz3BBbV0mGUQXMIFU7l:-Kz3BBbV0mGUQXMIFU7m:bxxy689) ([raw file](https://github.com/stratumn/sdk/blob/005fc4792355073553323f3cc5c4b4306d31b1d3/couchstore/batch.go#L42)):*
> ```Go
> 			_, err = b.originalCouchStore.DeleteValue(op.Key)
> 		default:
> 			err = fmt.Errorf("Invalid Batch operation type: %v", op.OpType)
> ```

It's better to use github.com/pkg/errors than fmt.Errorf
https://godoc.org/github.com/pkg/errors#Errorf

---

*[couchstore/batch.go, line 57 at r2](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz3Asa9C77xx7aFJHzq:-Kz3Asa9C77xx7aFJHzr:b-ya81ng) ([raw file](https://github.com/stratumn/sdk/blob/005fc4792355073553323f3cc5c4b4306d31b1d3/couchstore/batch.go#L57)):*
> ```Go
> 			_, err = b.originalCouchStore.DeleteSegment(op.LinkHash)
> 		default:
> 			err = fmt.Errorf("Invalid Batch operation type: %v", op.OpType)
> ```

Same as above

---

*[couchstore/couchstore.go, line 72 at r2](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz2nhWuaJc5_mhoDpZx:-Kz3BQsUV8yNLziuEcv-:b-5e5j0q) ([raw file](https://github.com/stratumn/sdk/blob/005fc4792355073553323f3cc5c4b4306d31b1d3/couchstore/couchstore.go#L72)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: Errorf already takes a format string as input, no need for the inner fmt.Sprintf, I think you can directly write:
fmt.Errorf("CouchDB returned status code %v, expected 200", resp.StatusCode)
</blockquote></details>

Or use github.com/pkg/errors instead of "errors"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: 4 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[couchstore/api.go, line 28 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-furPNacuNoVeB5wY:-Kz3g3Mup8mUBRvjnldn:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L28)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Sounds good then !
</blockquote></details>

Done.

---

*[couchstore/api.go, line 64 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-gH4ISLMY5Jy63wTU:-Kz3g4PFvkFcOe1YxKBs:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/api.go#L64)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Then do you mind putting a more explicit comment, something like "This field is only populated when the document contains a value"?
</blockquote></details>

Done.

---

*[couchstore/batch.go, line 42 at r2](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz3BBbV0mGUQXMIFU7l:-Kz3fzMINEoJpcFYhMmn:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/005fc4792355073553323f3cc5c4b4306d31b1d3/couchstore/batch.go#L42)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

It's better to use github.com/pkg/errors than fmt.Errorf
https://godoc.org/github.com/pkg/errors#Errorf
</blockquote></details>

Done.

---

*[couchstore/batch.go, line 57 at r2](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz3Asa9C77xx7aFJHzq:-Kz3g-bTdeShvIDg8TSl:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/005fc4792355073553323f3cc5c4b4306d31b1d3/couchstore/batch.go#L57)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[couchstore/couchstore.go, line 167 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-iKBWsFdkiGExzxJk:-Kz3g6YYqsaZAfDKHK3i:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/couchstore/couchstore.go#L167)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Ah good point, then it makes sense that the store has to do it
</blockquote></details>

Done.

---

*[couchstore/couchstore.go, line 72 at r2](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz2nhWuaJc5_mhoDpZx:-Kz3g5i5LJGfAjk0gCMV:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/005fc4792355073553323f3cc5c4b4306d31b1d3/couchstore/couchstore.go#L72)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Or use github.com/pkg/errors instead of "errors"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234#-:-Kz3po8qpchvG8Sj-Ky7:bnfp4nl)*

**Comment by alexppxela** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[couchstore/api.go, line 50 at r3](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz8TxQ4wdRcq_5oULtm:-Kz8TxQ4wdRcq_5oULtn:bhnrgy0) ([raw file](https://github.com/stratumn/sdk/blob/19269d53ad846980ac1b95cadcbe1ba302843a80/couchstore/api.go#L50)):*
> ```Go
> }
> 
> func (c *CouchResponseStatus) error() string {
> ```

This function can return an error to avoid all errors.New() below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by piedup** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[couchstore/api.go, line 50 at r3](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz8TxQ4wdRcq_5oULtm:-KzNjOnslB4PWJMO7sy1:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/19269d53ad846980ac1b95cadcbe1ba302843a80/couchstore/api.go#L50)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

This function can return an error to avoid all errors.New() below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234#-:-KzNl57I2csAI91MAoKp:bnfp4nl)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/234#-Kz-rALUzs9ps1UN_Zf9:-KzOWrrXOsE-xXpcDOAc:bvznys8) ([raw file](https://github.com/stratumn/sdk/blob/56f7d368c94e1220c16fd95a5542fdcf00e89513/.travis.yml#L17)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Otherwise what I have done in the fabricstore is use a flag -integration. When passing this flag to go test it will run all the integration tests such as couchdb. Travis could run -integration on deployment, but default behaviour would be to run without the -integration flag. The only downside is that you have to add `integration = flag.String("integration", false, "Run integration tests")` in all test files of the sdk.
</blockquote></details>

I think it'd be a good idea to do it in main with no integration flag but let's do that in another PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/234)*

**Pull request merged**
