### PR TITLE
agent, agent-client: define interfaces

### PR DESCRIPTION
**Pull request by simonvadee**
Sorry about the PR size, but since it's mainly interface definition it should be a bit easier to review than the TMPop one !

The goal here is not to add an agent-go, but rather the agent-client-go that we will need for our other little project (wink wink). However, I think it's a good idea to define the interfaces now since a majority of them will be shared by the agent and the client. Moreover, `golang/mock` allows us to generate a mock based on an interface (`agent/mock.go` is auto-generated), which can be useful for testing.

I did not create interfaces for `storeClient` and `fossilizerClient` since they won't be used by the client but I can fix this if you think it's a pity to have `interface{}` in the code.

Let me know what you think !

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/281)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[agent/plugin.go, line 16 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qs6Lua2CZIRkUmez2:-L-qs6LvLEAG8WNahI27:b-k3gbwl) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/plugin.go#L16)):*
> ```Go
> 	WillCreate(*cs.Link)
> 	DidCreateLink(*cs.Link)
> 	DidCreateSegment(*cs.Segment)
> ```

Are both of those still useful after the store migration?
It looks like we only need one of them (probably DidCreateLink)

---

*[agent/plugin.go, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qsKTGM8hRg0Ptgfj0:-L-qsKTGM8hRg0Ptgfj1:byfw7ww) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/plugin.go#L17)):*
> ```Go
> 	DidCreateLink(*cs.Link)
> 	DidCreateSegment(*cs.Segment)
> 	FilterSegment(*cs.Segment)
> ```

What does this do? Quickly commenting the methods would be useful for noobies like me :)

---

*[agent/client/client.go, line 22 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qsduvFsnoEJxpFp8x:-L-qsduvFsnoEJxpFp8y:b-uewm3f) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/client/client.go#L22)):*
> ```Go
> type AgentClient interface {
> 	CreateMap(process string, refs []map[string]string, args ...string) (*cs.Segment, error)
> 	CreateSegment(process, linkHash, action string, refs []map[string]string, args ...string) (*cs.Segment, error)
> ```

This should probably become CreateLink...I think Mourad is working on the agent-js migration, you should probably sync with him to align

---

*[agent/client/client_test.go, line 13 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qt7ipKD2nRkK2_diK:-L-qt7ipKD2nRkK2_diL:b-bwi7hk) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/client/client_test.go#L13)):*
> ```Go
> func TestNewAgentClient(t *testing.T) {
> 	client, err := client.NewAgentClient(agentUrl)
> 	if err != nil {
> ```

Maybe use stretchr/testify/assert in all new projects to replace this by assert.NoError(t, err)?
And replace the other test statements as well to use assertions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Comment by simonvadee** [comment]
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[agent/plugin.go, line 16 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qs6Lua2CZIRkUmez2:-L-vz0XOCQ025IovFJQW:b-vx0u51) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/plugin.go#L16)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Are both of those still useful after the store migration?
It looks like we only need one of them (probably DidCreateLink)
</blockquote></details>

Indeed !

---

*[agent/plugin.go, line 17 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qsKTGM8hRg0Ptgfj0:-L-vz2HbbKXh1utCRho4:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/plugin.go#L17)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

What does this do? Quickly commenting the methods would be useful for noobies like me :)
</blockquote></details>

Done.

---

*[agent/client/client.go, line 22 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qsduvFsnoEJxpFp8x:-L03cOxapQMQLe8IqYU_:bq5fzed) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/client/client.go#L22)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

This should probably become CreateLink...I think Mourad is working on the agent-js migration, you should probably sync with him to align
</blockquote></details>

will do !

---

*[agent/client/client_test.go, line 13 at r1](https://reviewable.io:443/reviews/stratumn/sdk/281#-L-qt7ipKD2nRkK2_diK:-L-w-qFM62I5xkKGdLL5:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/f85928dfd551acd3ac0430a444a0cdb0ee77853d/agent/client/client_test.go#L13)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Maybe use stretchr/testify/assert in all new projects to replace this by assert.NoError(t, err)?
And replace the other test statements as well to use assertions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Comment by such** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[agent/agent.go, line 29 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03ihL-_61RmuNXIQz_:-L03ihL-_61RmuNXIQza:bgclg77) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/agent.go#L29)):*
> ```Go
> // ProcessOptions can be used to configure a process when creating a new one
> type ProcessOptions struct {
> 	Salt             string  `json:"salt"`
> ```

This will be useless after @bejito commit I think. Can you confirm?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[agent/client/client.go, line 83 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03n3Z8xtucGZqZnIg6:-L03n3Z8xtucGZqZnIg7:b-4x5bla) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/client/client.go#L83)):*
> ```Go
> }
> 
> func (a *agentClient) FindSegments(fitler *store.SegmentFilter) (cs.SegmentSlice, error) {
> ```

nit: filter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281#-:-L03nDHEhDWPD0WwTh4Y:bnfp4nl)*

**Comment by bejito** [comment]
*[agent/agent.go, line 29 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03ihL-_61RmuNXIQz_:-L03oZo7ODsucYXr6dpu:b-fc4vc2) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/agent.go#L29)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

This will be useless after @bejito commit I think. Can you confirm?
</blockquote></details>

Since that salt was only used in the fossilization callback, it will become useless yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Comment by alexppxela** [comment]
Reviewed 4 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[agent/mock.go, line 1 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03p022bQhGFkeKe3f9:-L03p022bQhGFkeKe3fA:bz9avua) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/mock.go#L1)):*
> ```Go
> // Code generated by MockGen. DO NOT EDIT.
> ```

Is it necessary to commit generated files?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[agent/agent.go, line 29 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03ihL-_61RmuNXIQz_:-L03qoRxgfnCRBF9qSmC:bb70vaa) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/agent.go#L29)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

Since that salt was only used in the fossilization callback, it will become useless yes.
</blockquote></details>

OK !

---

*[agent/mock.go, line 1 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03p022bQhGFkeKe3f9:-L03qPoho7X7YOiwr3Nq:b-6vu3m1) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/mock.go#L1)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Is it necessary to commit generated files?
</blockquote></details>

I think in this case it's the right thing to do, it prevents us from adding an other dependency to the project and since this is based solely on the agent's interface, it will probably not change often. What do you think ?

---

*[agent/client/client.go, line 83 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03n3Z8xtucGZqZnIg6:-L03qscLJdLkHwdROyp7:bn932oz) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/client/client.go#L83)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: filter
</blockquote></details>

you must have 12/10 on both eyes to be able to spot these things

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[agent/client/client.go, line 83 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03n3Z8xtucGZqZnIg6:-L03sSV87otYBQvk-ldp:b-c1wfj7) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/client/client.go#L83)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

you must have 12/10 on both eyes to be able to spot these things
</blockquote></details>

https://tinyurl.com/ybeln5ch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 3 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[agent/mock.go, line 1 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03p022bQhGFkeKe3f9:-L03s8J6-LA2JaGNea7B:b-yd8jb8) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/mock.go#L1)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

I think in this case it's the right thing to do, it prevents us from adding an other dependency to the project and since this is based solely on the agent's interface, it will probably not change often. What do you think ?
</blockquote></details>

If it "never" changes, ok to do not introduce another dependency.

---

*[agent/client/client.go, line 83 at r2](https://reviewable.io:443/reviews/stratumn/sdk/281#-L03n3Z8xtucGZqZnIg6:-L03snP0WkoJuonf9R89:bb7hf0f) ([raw file](https://github.com/stratumn/sdk/blob/bdf96dfbf7d342cf1bc984ce44b9037aa469c0a7/agent/client/client.go#L83)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

https://tinyurl.com/ybeln5ch
</blockquote></details>

hehe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281#-:-L03styn84_kDU4BrJqj:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/281)*

**Pull request merged**
