### PR TITLE
couchstore: update to the new store interface

### PR DESCRIPTION
**Pull request by alexppxela**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/259)

### CODE REVIEW

**Comment by piedup** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[couchstore/api.go, line 145 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1K_FGVuKHXF7RnrOy:-L-1K_FGVuKHXF7RnrOz:brndn2i) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/api.go#L145)):*
> ```Go
> 	}
> 
> 	currentLinkDoc, err := c.getDocument(dbLink, linkHash.String())
> ```

Since Link is immutable we shouldn't check for existing Link but handle document already exists error when trying to save the Link. So maybe saveDocuments should be updated so that it handles the error rather than swallowing the error if map doesn't exist.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by t-bast** [comment]
:lgtm:
Thank you!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[couchstore/api.go, line 134 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1JSRQs74M5XLram8t:-L-1JSRQs74M5XLram8u:b-p5f0n8) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/api.go#L134)):*
> ```Go
> 
> func (c *CouchStore) createLink(link *cs.Link) error {
> 	linkHash, err := link.Hash()
> ```

nit: you have a link.HashString() function on link available (since you only use it as a string afterwards and currently call String() multiple times)

---

*[couchstore/api.go, line 184 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1JqyMRpUCuZIsOVE0:-L-1JqyMRpUCuZIsOVE1:bnbnlb) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/api.go#L184)):*
> ```Go
> 	// COMPLETE one. This won't be necessary after the store interface
> 	// update, but meanwhile we need to correctly update the existing
> 	// evidence.
> ```

Sorry, this is still needed because TMPoP isn't migrated yet :/
I'll remove this from all stores once TMPoP is migrated

---

*[couchstore/couchstore.go, line 128 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1LocEFFkF60FRTcwp:-L-1LocFfwQS4wv1t6y5:b8q2lnh) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/couchstore.go#L128)):*
> ```Go
> 	}
> 	c.notifyEvent(store.SavedLink, link)
> 	return link.Hash()
> ```

If you don't specify the second argument it returns a nil one by default? I didn't know that, looks more concise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259#-:-L-1MwJVIroUIqACaW44:b44p7rl)*

**Comment by piedup** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[couchstore/api.go, line 133 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1OBF7cpXOaK0Ruu5h:-L-1OBF7cpXOaK0Ruu5i:b-611vic) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/api.go#L133)):*
> ```Go
> }
> 
> func (c *CouchStore) createLink(link *cs.Link) error {
> ```

Should this function return the linkHash along the error? It could then be used when returning linkHash from CreateLink without having to recompute the HashLink.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by piedup** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by such** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[couchstore/couchstore.go, line 128 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1LocEFFkF60FRTcwp:-L-1vhoBbMsNXss6s0Fg:b-rlm5o7) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/couchstore.go#L128)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

If you don't specify the second argument it returns a nil one by default? I didn't know that, looks more concise
</blockquote></details>

@t-bast no it's just that `Hash` returns two values :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[couchstore/couchstore.go, line 128 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1LocEFFkF60FRTcwp:-L-1xHdjQ3lRdVHBkVw4:bqi7wz6) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/couchstore.go#L128)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

@t-bast no it's just that `Hash` returns two values :)
</blockquote></details>

Ahah good point. Got to get used to Go's multiple return values :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[couchstore/api.go, line 133 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1OBF7cpXOaK0Ruu5h:-L-1xiugaU-777MJimOp:b-wztqm0) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/api.go#L133)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Should this function return the linkHash along the error? It could then be used when returning linkHash from CreateLink without having to recompute the HashLink.
</blockquote></details>

Well spotted
Done

---

*[couchstore/api.go, line 134 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1JSRQs74M5XLram8t:-L-22rGYnCH0QWfAR9Uw:bb7f2mf) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/api.go#L134)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: you have a link.HashString() function on link available (since you only use it as a string afterwards and currently call String() multiple times)
</blockquote></details>

done

---

*[couchstore/api.go, line 145 at r1](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-1K_FGVuKHXF7RnrOy:-L-24SicU5O5XixmXJTs:b-l4bzzg) ([raw file](https://github.com/stratumn/sdk/blob/dc4e4d7e7069990583f1969a298783e1bf8ba9eb/couchstore/api.go#L145)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Since Link is immutable we shouldn't check for existing Link but handle document already exists error when trying to save the Link. So maybe saveDocuments should be updated so that it handles the error rather than swallowing the error if map doesn't exist.
</blockquote></details>

You're true. It is better!
I have write the code in comment and code has to be switched when resolving issue #264 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[couchstore/api.go, line 148 at r2](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-2DYoPUmfDsa0V9Ect:-L-2DYoPUmfDsa0V9Ecu:b-vlmw37) ([raw file](https://github.com/stratumn/sdk/blob/ff280a5e617f74f2f75325570cae28218437294a/couchstore/api.go#L148)):*
> ```Go
> 
> 	// <<<<<
> 	currentLinkDoc, err := c.getDocument(dbLink, linkHash.String())
> ```

nit: here you can use linkHashStr instead of recomputing .String()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[couchstore/api.go, line 148 at r2](https://reviewable.io:443/reviews/stratumn/sdk/259#-L-2DYoPUmfDsa0V9Ect:-L-2E-k_0JobmLvHBVSp:buuww1t) ([raw file](https://github.com/stratumn/sdk/blob/ff280a5e617f74f2f75325570cae28218437294a/couchstore/api.go#L148)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: here you can use linkHashStr instead of recomputing .String()
</blockquote></details>

Grrr oops, I had fixed it in commented target version just below...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259)*

**Comment by piedup** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259#-:-L-2ELY6iGEVCxCA_KZm:bnfp4nl)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/259#-:-L-2Eg_tUcSYfEC-1VXs:bnfp4nl)*

**Comment by alexppxela** [comment]
Resolves #252

**Pull request merged**
