### PR TITLE
storehttp: parse linkHashes in parseSegmentFilter

### LINKED ISSUE #293: parseSegmentFilter does not parse LinkHashes
```go
type SegmentFilter struct {
	Pagination `json:"pagination"`

	MapIDs []string `json:"mapIds" url:"mapIds,brackets"`

	Process string `json:"process" url:"-"`

	PrevLinkHash *string `json:"prevLinkHash" url:"prevLinkHash"`

	LinkHashes []*types.Bytes32 `json:"linkHashes" url:"linkHashes,brackets"`

	Tags []string `json:"tags" url:"tags"`
}

func parseSegmentFilter(r *http.Request) (*store.SegmentFilter, error) {
...stuff...
return &store.SegmentFilter{
		Pagination:   *pagination,
		MapIDs:       mapIDs,
		Process:      process,
		PrevLinkHash: prevLinkHash,
		Tags:         tags,
	}, nil
```

It seems that `parseSegmentFilter` is missing the deserialisation of the `LinkHashes` array contained in the URL parameters. A test should be added to cover this.

### PR DESCRIPTION
**Pull request by simonvadee**
Fix #293

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/294)

### CODE REVIEW

**Comment by conord33** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/294#-:-L0F2Yg8afvvBt1k4hOl:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/storehttp/storehttp_test.go, line 405 at r1](https://reviewable.io:443/reviews/stratumn/sdk/294#-L0FC9TjeS3_Eo5pZZ2A:-L0FC9TjeS3_Eo5pZZ2B:b28s0d7) ([raw file](https://github.com/stratumn/sdk/blob/f2d3b97808fe2ab6e58f081489e554341d1ffeb7/store/storehttp/storehttp_test.go#L405)):*
> ```Go
> 	var s2 cs.SegmentSlice
> 	w, err := testutil.RequestJSON(s.ServeHTTP, "GET", "/segments?offset=1&limit=2&linkHashes[]="+zeros+"&linkHashes%5B%5D="+zeros, nil, &s2)
> 	if err != nil {
> ```

Maybe use testify/assert ? (no need to update the other tests, but new ones should use it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/294)*

**Comment by simonvadee** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[store/storehttp/storehttp_test.go, line 405 at r1](https://reviewable.io:443/reviews/stratumn/sdk/294#-L0FC9TjeS3_Eo5pZZ2A:-L0FDkVDbSIEhEmuoZip:bm6r4wi) ([raw file](https://github.com/stratumn/sdk/blob/f2d3b97808fe2ab6e58f081489e554341d1ffeb7/store/storehttp/storehttp_test.go#L405)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Maybe use testify/assert ? (no need to update the other tests, but new ones should use it)
</blockquote></details>

Done. (It's a lot cleaner indeed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/294)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/294#-:-L0FIhy0D8zTWB9Nw2cJ:bnfp4nl)*

**Pull request merged**
