### PR TITLE
cs: References validation

### PR DESCRIPTION
**Pull request by alexppxela**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/220)

### CODE REVIEW

**Comment by alexppxela** [comment]
*[cs/util_test.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-Ky0WSyBxyBKQIaWYxjG:-Ky0WSyBxyBKQIaWYxjH:bak7kxx) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/util_test.go#L38)):*
> ```Go
> 
> func testSegmentValidateError(t *testing.T, s *cs.Segment, getSegment cs.GetSegmentFunc, want string) {
> 	innerTestSegmentValidate(t, s, getSegment, want, strEqual)
> ```

I am interested in a solution to do not write `strEqual` to be passed to `innerTestSegmentValidate`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220)*

**Comment by t-bast** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cs/cs.go, line 89 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-Ky1dQY7dJ4Z8rFdtOFS:-Ky1dQY7dJ4Z8rFdtOFT:b9iifz8) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L89)):*
> ```Go
> }
> 
> func (s *Segment) validateReferences(getSegment GetSegmentFunc) error {
> ```

If I understand properly it does two things (for each ref):
  * If the ref directly contains a segment object, recursively validate it
  * If the ref contains a process and linkHash fetch the corresponding segment to simply verify that it exists -> don't we want to recursively validate that segment as well?

---

*[cs/cs_test.go, line 52 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-Ky1eVvzUHmoJzLA2u6f:-Ky1eVvzUHmoJzLA2u6g:b-rps89c) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs_test.go#L52)):*
> ```Go
> func TestSegmentValidate_valid(t *testing.T) {
> 	s := cstesting.RandomSegment()
> 	if err := s.Validate(nil); err != nil {
> ```

nit: maybe a default value of nil would be useful?

---

*[cs/util_test.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-Ky0WSyBxyBKQIaWYxjG:-Ky1g66y0WVx-HAldX7H:bvzjyow) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/util_test.go#L38)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I am interested in a solution to do not write `strEqual` to be passed to `innerTestSegmentValidate`
</blockquote></details>

Maybe something like https://golang.org/pkg/strings/#EqualFold ? It really looks like we should be able to find this in the std lib instead of having to write it ourselves, but I don't know much about Go yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cs/cs.go, line 89 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-KyQy9DsmZD524UB8kR_:-KyQy9DsmZD524UB8kRa:b-e5giup) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L89)):*
> ```Go
> }
> 
> func (s *Segment) validateReferences(getSegment GetSegmentFunc) error {
> ```

I feel like a lot of these validations could be addressed at parsing time. Since refs is in link.meta it makes it a bit difficult... It kinda make me regret this choice. What do you think? Do you see a workaround?

---

*[cs/cs.go, line 125 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-KyQy2--z5LC9QbzrmeP:-KyQy2--z5LC9QbzrmeQ:b-ryjrqo) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L125)):*
> ```Go
> 					}
> 				}
> 				// Segment from another process is not retrieved because it should be in another store
> ```

typo: should -> could

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cs/cs.go, line 89 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-Ky1dQY7dJ4Z8rFdtOFS:-KyRbgeENDKDcSOOF5lj:bdnfgff) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L89)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

If I understand properly it does two things (for each ref):
  * If the ref directly contains a segment object, recursively validate it
  * If the ref contains a process and linkHash fetch the corresponding segment to simply verify that it exists -> don't we want to recursively validate that segment as well?
</blockquote></details>

Yes
* Check if the given segment is valid (recursively if necessary)
* If the store retrieves a segment from its linkhash, it has been already validated

---

*[cs/cs.go, line 89 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-KyQy9DsmZD524UB8kR_:-KyRcAADMzLH1u_YmqsA:bvtucat) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L89)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I feel like a lot of these validations could be addressed at parsing time. Since refs is in link.meta it makes it a bit difficult... It kinda make me regret this choice. What do you think? Do you see a workaround?
</blockquote></details>

Except like evidences and name fields. Or generate a sub json format from the ref content.
I'll try tomorrow, it should be prettier

---

*[cs/cs_test.go, line 52 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-Ky1eVvzUHmoJzLA2u6f:-KyRdK8i6hjL1KsbGMlT:bxt51e7) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs_test.go#L52)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: maybe a default value of nil would be useful?
</blockquote></details>

If you prefer, it could

---

*[cs/util_test.go, line 38 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-Ky0WSyBxyBKQIaWYxjG:-KyRdVvrnsoM2bPCL8O-:brgevnx) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/util_test.go#L38)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Maybe something like https://golang.org/pkg/strings/#EqualFold ? It really looks like we should be able to find this in the std lib instead of having to write it ourselves, but I don't know much about Go yet
</blockquote></details>

I have seen this function, it should be ok because it is for tests but the behavior is not exactly the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220)*

**Comment by alexppxela** [comment]
*[cs/cs.go, line 89 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-KyQy9DsmZD524UB8kR_:-KyavGaCe66_Nn03hRZ1:b-dmcku0) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L89)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Except like evidences and name fields. Or generate a sub json format from the ref content.
I'll try tomorrow, it should be prettier
</blockquote></details>

I thought that marshal/unmarshal in a typed structure will work but no :(
Do you know why marshal marshals as a string and not recursively?
To work, we should transform marshall output like this...
```go

type structuredRef struct {
	Segment  Segment `json:"segment,omitempty"`
	Process  string  `json:"process,omitempty"`
	LinkHash string  `json:"linkHash,omitempty"`
}

func (s *Segment) validateReferences(getSegment GetSegmentFunc) error {
	if refs, ok := s.Link.Meta["refs"].([]interface{}); ok {
		refBytes, _ := json.Marshal(refs)
		var structuredRefs []structuredRef
		refBytes = []byte(strings.Replace(string(refBytes), "\\\"", "\"", -1))
		refBytes = []byte(strings.Replace(string(refBytes), "\"segment\":\"{", "\"segment\":{", -1))
		refBytes = []byte(strings.Replace(string(refBytes), "}}}\"}]", "}}}}]", -1))
		if err := json.Unmarshal(refBytes, &structuredRefs); err != nil {
			return errors.WithMessage(err, "invalid link.meta.refs")
		}

		for refIdx, ref := range structuredRefs {
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220)*

**Comment by alexppxela** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[cs/cs.go, line 89 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-KyQy9DsmZD524UB8kR_:-Kz4foneQjbiAed03ALR:b-54as48) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L89)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I thought that marshal/unmarshal in a typed structure will work but no :(
Do you know why marshal marshals as a string and not recursively?
To work, we should transform marshall output like this...
```go

type structuredRef struct {
	Segment  Segment `json:"segment,omitempty"`
	Process  string  `json:"process,omitempty"`
	LinkHash string  `json:"linkHash,omitempty"`
}

func (s *Segment) validateReferences(getSegment GetSegmentFunc) error {
	if refs, ok := s.Link.Meta["refs"].([]interface{}); ok {
		refBytes, _ := json.Marshal(refs)
		var structuredRefs []structuredRef
		refBytes = []byte(strings.Replace(string(refBytes), "\\\"", "\"", -1))
		refBytes = []byte(strings.Replace(string(refBytes), "\"segment\":\"{", "\"segment\":{", -1))
		refBytes = []byte(strings.Replace(string(refBytes), "}}}\"}]", "}}}}]", -1))
		if err := json.Unmarshal(refBytes, &structuredRefs); err != nil {
			return errors.WithMessage(err, "invalid link.meta.refs")
		}

		for refIdx, ref := range structuredRefs {
...
```
</blockquote></details>

As discuss, workaround is to do link Meta and name fields in link keeping a `Data` map.
Now, this _ugly_ code is centralized and we can hope that we will find a technic later to cast properly nested json structure.

---

*[cs/cs.go, line 125 at r1](https://reviewable.io:443/reviews/stratumn/sdk/220#-KyQy2--z5LC9QbzrmeP:-Kz4ffc_Z5inZvLIoDL-:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/f420377106c7bcf39bb4cce66178ae1b8e23c11c/cs/cs.go#L125)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

typo: should -> could
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220#-:-KzNqSAxGjHkfBEiLNvx:bnfp4nl)*

**Comment by alexppxela** [comment]
@such I need another validation due to `master` rebase conflicts

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220#-:-KzO0bH5MdwzBvIlp50r:b-is7mot)*

**Comment by such** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/220)*

**Pull request merged**
