### PR TITLE
stores: store v2 test cases

### PR DESCRIPTION
**Pull request by t-bast**
Creating a test suite for the updated store interfaces.
I tried to think of a clever way to do it, but I think that in fact it's easier to keep it simple: so I duplicated almost every test and did small changes to make them run against the new interface.
So the resulting PR is quite big, but most of the code is copy-paste (which is bad, but since the goal is to remove completely the code that was copied once the migration is complete, I think it's ok to have that temporary duplication because it's much simpler than complex refactorings).
And in case you are wondering, yeah it was really painful to do :)
https://imgflip.com/i/1zvuwy

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/250)

### CODE REVIEW

**Comment by alexppxela** [comment]
I like your link ;)

---

Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[filestore/filestore.go, line 123 at r1](https://reviewable.io:443/reviews/stratumn/sdk/250#-KzhGihdXEmCVfHit0wO:-KzhGihdXEmCVfHit0wP:b-xsmc5x) ([raw file](https://github.com/stratumn/sdk/blob/996e0302154bad3da5daa40076b4e6e4023a4ab9/filestore/filestore.go#L123)):*
> ```Go
> // NewBatchV2 implements github.com/stratumn/sdk/store.AdapterV2.NewBatchV2.
> func (a *FileStore) NewBatchV2() (store.BatchV2, error) {
> 	return nil, nil
> ```

Why do you not implement BatchV2? It'll be for a next PR?

---

*[store/storetestcases/findsegments.go, line 99 at r1](https://reviewable.io:443/reviews/stratumn/sdk/250#-KzhFT-m1vtQBW92Ftpi:-KzhFT-m1vtQBW92Ftpj:b-wqf12z) ([raw file](https://github.com/stratumn/sdk/blob/996e0302154bad3da5daa40076b4e6e4023a4ab9/store/storetestcases/findsegments.go#L99)):*
> ```Go
> 
> // TestFindSegmentsV2 tests what happens when you search with default pagination.
> func (f Factory) TestFindSegmentsV2(t *testing.T) {
> ```

I trust your copy/paste for this file ;)

---

*[store/storetestcases/storetestcases.go, line 435 at r1](https://reviewable.io:443/reviews/stratumn/sdk/250#-KzhGYtDoXl2N0Cvc6W-:-KzhGYtDoXl2N0Cvc6W0:bf93dbx) ([raw file](https://github.com/stratumn/sdk/blob/996e0302154bad3da5daa40076b4e6e4023a4ab9/store/storetestcases/storetestcases.go#L435)):*
> ```Go
> }
> 
> func (f Factory) initAdapterV2B(b *testing.B) store.AdapterV2 {
> ```

You forgot benchmarkV2 test instantiation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/250#-:-KzhDPzs-3-lKXmdHnUZ:b-40pu6k)*

**Comment by alexppxela** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/250)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[filestore/filestore.go, line 123 at r1](https://reviewable.io:443/reviews/stratumn/sdk/250#-KzhGihdXEmCVfHit0wO:-KzhHFq5vWeaCTSfbTVs:b760oc3) ([raw file](https://github.com/stratumn/sdk/blob/996e0302154bad3da5daa40076b4e6e4023a4ab9/filestore/filestore.go#L123)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why do you not implement BatchV2? It'll be for a next PR?
</blockquote></details>

Yes exactly, I haven't completely figured out yet what we need from our batch system and I think it's going to end up simpler than the current once, so I'm leaving it for later :)

---

*[store/storetestcases/findsegments.go, line 99 at r1](https://reviewable.io:443/reviews/stratumn/sdk/250#-KzhFT-m1vtQBW92Ftpi:-KzhHMu5jWpfDNHH8zys:b6374gx) ([raw file](https://github.com/stratumn/sdk/blob/996e0302154bad3da5daa40076b4e6e4023a4ab9/store/storetestcases/findsegments.go#L99)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I trust your copy/paste for this file ;)
</blockquote></details>

Oh yeah, this was the most painful one ;)
But since I copy-pasted each test, simply added v2 to the methods and the tests pass, I think it's somewhat trustable

---

*[store/storetestcases/storetestcases.go, line 435 at r1](https://reviewable.io:443/reviews/stratumn/sdk/250#-KzhGYtDoXl2N0Cvc6W-:-KzhHWV3iT-Jh8BHZEcv:bp8nik4) ([raw file](https://github.com/stratumn/sdk/blob/996e0302154bad3da5daa40076b4e6e4023a4ab9/store/storetestcases/storetestcases.go#L435)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

You forgot benchmarkV2 test instantiation
</blockquote></details>

Yeah I was thinking that I didn't want to duplicate the benchmark tests too because it's a lot of useless work...
I think instead for benchmark we'll just update the existing tests to target only the new store interface once we finish the migration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/250)*

**Comment by alexppxela** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[store/storetestcases/storetestcases.go, line 435 at r1](https://reviewable.io:443/reviews/stratumn/sdk/250#-KzhGYtDoXl2N0Cvc6W-:-KzhLAvfRXL6WGFFdoJ5:bka5hu6) ([raw file](https://github.com/stratumn/sdk/blob/996e0302154bad3da5daa40076b4e6e4023a4ab9/store/storetestcases/storetestcases.go#L435)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Yeah I was thinking that I didn't want to duplicate the benchmark tests too because it's a lot of useless work...
I think instead for benchmark we'll just update the existing tests to target only the new store interface once we finish the migration
</blockquote></details>

Ok for me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/250#-:-KzhLK9L9g2xNa7t_xhu:bnfp4nl)*

**Pull request merged**
