### PR TITLE
tmpop: fix deadlock with transactional database

### PR DESCRIPTION
**Pull request by such**
In postgrestmpop, we use database transactions for Batch.
But whenever a transaction is delivered, it has already been checked and obviously `checkedSegments`, the batch of checked segments since the last commit, have not been commited. They have not been rollbacked either because CheckTx on new transactions that are inserted in the mempool can still be called while a block is being delivered.
This leads to DeliverTx hanging.
Since checkedTransactions will never be commited anyway, it's safe to use a BufferedBatch (even though reads will be less performant).

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/236)

### CODE REVIEW

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236#-:-Kz4lAtnKo5Kq9Nh7jPc:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bufferedbatch/batch.go, line 251 at r2](https://reviewable.io:443/reviews/stratumn/sdk/236#-Kz99zuY8KtfBJoq3ua-:-Kz99zuY8KtfBJoq3ua0:b-zhs6i) ([raw file](https://github.com/stratumn/sdk/blob/ad3b16e12efe49140e3b474cd408515933e330d4/bufferedbatch/batch.go#L251)):*
> ```Go
> // Write implements github.com/stratumn/sdk/store.Batch.Write
> func (b *Batch) Write() (err error) {
> 	for _, op := range b.ValueOps {
> ```

I'm not sure it's a good idea to set the err value in a loop if you don't break when err isn't nil.
If for example the first op produces an error, you will set "err" to a non-nil value.
But if the second op doesn't produce an error, you will re-write err with nil.
And when you'll check nil after the for loop, you'll think everything is ok.

---

*[bufferedbatch/batch.go, line 266 at r2](https://reviewable.io:443/reviews/stratumn/sdk/236#-Kz9AKxUhXpesKom3bVH:-Kz9AKxUhXpesKom3bVI:brinekk) ([raw file](https://github.com/stratumn/sdk/blob/ad3b16e12efe49140e3b474cd408515933e330d4/bufferedbatch/batch.go#L266)):*
> ```Go
> 	}
> 
> 	for _, op := range b.SegmentOps {
> ```

Same issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bufferedbatch/batch.go, line 251 at r2](https://reviewable.io:443/reviews/stratumn/sdk/236#-Kz99zuY8KtfBJoq3ua-:-Kz9Ay56JFA1W5RwpVye:bp85q41) ([raw file](https://github.com/stratumn/sdk/blob/ad3b16e12efe49140e3b474cd408515933e330d4/bufferedbatch/batch.go#L251)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I'm not sure it's a good idea to set the err value in a loop if you don't break when err isn't nil.
If for example the first op produces an error, you will set "err" to a non-nil value.
But if the second op doesn't produce an error, you will re-write err with nil.
And when you'll check nil after the for loop, you'll think everything is ok.
</blockquote></details>

You're right that's pretty bad. I just moved the code from somewhere else (but I had written it in the first place I think!).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bufferedbatch/batch.go, line 251 at r2](https://reviewable.io:443/reviews/stratumn/sdk/236#-Kz99zuY8KtfBJoq3ua-:-Kz9BfEUgb1vzMTeBHbO:b32vhw) ([raw file](https://github.com/stratumn/sdk/blob/ad3b16e12efe49140e3b474cd408515933e330d4/bufferedbatch/batch.go#L251)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

You're right that's pretty bad. I just moved the code from somewhere else (but I had written it in the first place I think!).
</blockquote></details>

:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236)*

**Comment by such** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[bufferedbatch/batch.go, line 251 at r2](https://reviewable.io:443/reviews/stratumn/sdk/236#-Kz99zuY8KtfBJoq3ua-:-Kz9CvenQVEDszdNm2xg:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/ad3b16e12efe49140e3b474cd408515933e330d4/bufferedbatch/batch.go#L251)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

:)
</blockquote></details>

Done.

---

*[bufferedbatch/batch.go, line 266 at r2](https://reviewable.io:443/reviews/stratumn/sdk/236#-Kz9AKxUhXpesKom3bVH:-Kz9Cwj_t1oII05hwggn:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/ad3b16e12efe49140e3b474cd408515933e330d4/bufferedbatch/batch.go#L266)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Same issue
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236)*

**Comment by t-bast** [comment]
nit: it might also be useful to add a unit test to cover this, so that we're covered for future changes :)

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236#-:-Kz9DW69rXECbr0FbBgs:bpxa5zm)*

**Comment by such** [comment]
the original issue you mean? it's not that easy since we don't have transactional databases in the sdk right now... some tests will be added in goprivate though (I create this issue yesterday: https://github.com/stratumn/sdk/issues/235)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236#-:-Kz9Ge6uGrJEeFOoWjzU:b-xcpbfk)*

**Comment by t-bast** [comment]
Sorry, I meant the issue with the errors not being caught because of the missing break

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236#-:-Kz9Ike_pkMmiX5Vkvyq:b-wujt3t)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/236#-:-Kz9Yjo3qqxMAjXt6fJ1:bnfp4nl)*

**Pull request merged**
