### PR TITLE
bufferedbatch: batch v2 implementation

### PR DESCRIPTION
**Pull request by t-bast**
Implement a batch v2 buffered batch.
It will most likely be used as-is in all our stores since the batch is now simpler than what it was previously.
Note: I found it horrible to have to manually implement the mocks, we need to take some time to find a good package to do that for us (and at the same time add a good assertions library for our unit tests).

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/258)

### CODE REVIEW

**Comment by alexppxela** [comment]
:lgtm:
Good job :+1: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cs/cs.go, line 332 at r1](https://reviewable.io:443/reviews/stratumn/sdk/258#-L-0dvJTsY4xv6m7tLa6:-L-0dvJUVmpwVdQlo-e0:b-otxfxc) ([raw file](https://github.com/stratumn/sdk/blob/b04fd07f6c75196aea5bf26508d63506c59c7df8/cs/cs.go#L332)):*
> ```Go
> // Segmentify returns a segment from a link,
> // filling the link hash and appropriate meta.
> func (l *Link) Segmentify() *Segment {
> ```

Why `l` is a pointer?
This comment can be applied in function signatures above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/258#-:-L-0h0JLzmk6z_-1ZuhB:b-38vemf)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cs/cs.go, line 332 at r1](https://reviewable.io:443/reviews/stratumn/sdk/258#-L-0dvJTsY4xv6m7tLa6:-L-0l8SJ3cFKpWjLgcnF:bx2rzvf) ([raw file](https://github.com/stratumn/sdk/blob/b04fd07f6c75196aea5bf26508d63506c59c7df8/cs/cs.go#L332)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why `l` is a pointer?
This comment can be applied in function signatures above.
</blockquote></details>

Good point, it probably doesn't need to be a pointer. I'll update it and verify that it works correctly with a value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/258)*

**Comment by t-bast** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[cs/cs.go, line 332 at r1](https://reviewable.io:443/reviews/stratumn/sdk/258#-L-0dvJTsY4xv6m7tLa6:-L-0leNzFoMxiEJ5R_Mc:b-886gsx) ([raw file](https://github.com/stratumn/sdk/blob/b04fd07f6c75196aea5bf26508d63506c59c7df8/cs/cs.go#L332)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Good point, it probably doesn't need to be a pointer. I'll update it and verify that it works correctly with a value.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/258)*

**Comment by alexppxela** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/258)*

**Comment by such** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bufferedbatch/batchV2.go, line 76 at r2](https://reviewable.io:443/reviews/stratumn/sdk/258#-L-1-1ptkuTQAbFSw6xo:-L-1-1ptkuTQAbFSw6xp:b-l5u6nc) ([raw file](https://github.com/stratumn/sdk/blob/e7b30f79b071988d928941326ae44a905c6e87e8/bufferedbatch/batchV2.go#L76)):*
> ```Go
> 	for _, link := range b.Links {
> 		if filter.MatchLink(link) {
> 			segments = append(segments, link.Segmentify())
> ```

In retrospect, does it make sense that the BatchV2 implements `GetSegment` and `FindSegments` instead of `GetLink` and `FindLinks`? We are a bit lying here since we're actually returning `Links` wrapped in `Segments`. Maybe `GetSegment` and `FindSegments` is a higher level interface implemented only by adapters that have access to an `EvidenceStore` and a `LinkStore`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/258)*

**Comment by t-bast** [comment]
I think it makes sense to keep it like that because the batch contains the underlying store adapter and does GetSegment and FindSegment in both its batched data and the underlying adapter.
So it could return data with evidence if the underlying store adapter returns a segment with evidence.

The only issue I would see would be to do GetSegment on a link that's both in the batch and in the underlying store adapter:
  * if the underlying store adapter has some evidence, it would return it
  * but right now since we find it in the batch (without evidence), we return that link wrapped in a segment

I'm not sure this is a very valid scenario though, but we could fix this by always doing GetSegment in both the batch and the underlying store to enrich with the store's evidence. But since I think this situation shouldn't happen, I think it's fine to keep that way don't you think?

**Pull request merged**
