### PR TITLE
store: modifiy signature of NewSavedLinks

### PR DESCRIPTION
**Pull request by alexppxela**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/304)

### CODE REVIEW

**Comment by piedup** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/304#-:-L0j1lcMIDa-uaEVl0jf:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[store/event.go, line 44 at r1](https://reviewable.io:443/reviews/stratumn/sdk/304#-L0j15knIG3YrTBdnnIH:-L0j15koBhLJ3hujduH5:b-bj4lz7) ([raw file](https://github.com/stratumn/sdk/blob/149440e7564706a39dcb1874d3eb630955b2d5bd/store/event.go#L44)):*
> ```Go
> // NewSavedLinks creates a new event to notify links were saved.
> func NewSavedLinks(linkArgs ...*cs.Link) *Event {
> 	links := make([]*cs.Link, 0, len(linkArgs))
> ```

nit: the initial length can (should) be len(linkArgs) shouldn't it? why do you set it to 0 when you set the capacity to len(linkArgs)? It's worth setting both isn't it?

---

*[store/event.go, line 62 at r1](https://reviewable.io:443/reviews/stratumn/sdk/304#-L0j1aVjdnuDE2zz0p0O:-L0j1aVk82akZyVo4xeM:bopk6nj) ([raw file](https://github.com/stratumn/sdk/blob/149440e7564706a39dcb1874d3eb630955b2d5bd/store/event.go#L62)):*
> ```Go
> // AddSavedLinks adds links to the event.
> // It assumes the event is a correctly initialized SavedLinks event.
> func (event *Event) AddSavedLinks(links []*cs.Link) {
> ```

nit: this could also receive template args like the constructor, it's more elegant (I should have done it from the start)
And maybe in that case the AddSaveLink above isn't necessary anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/304)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[store/event.go, line 44 at r1](https://reviewable.io:443/reviews/stratumn/sdk/304#-L0j15knIG3YrTBdnnIH:-L0j3zRUhII77O-OVR9X:brwgwqx) ([raw file](https://github.com/stratumn/sdk/blob/149440e7564706a39dcb1874d3eb630955b2d5bd/store/event.go#L44)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: the initial length can (should) be len(linkArgs) shouldn't it? why do you set it to 0 when you set the capacity to len(linkArgs)? It's worth setting both isn't it?
</blockquote></details>

no, if `length = len(linkArgs)` links will begin with length nil elements. That's why I set the capacity and not the length.

---

*[store/event.go, line 62 at r1](https://reviewable.io:443/reviews/stratumn/sdk/304#-L0j1aVjdnuDE2zz0p0O:-L0j38_0UOMNyZbb_XWC:b-jgt7c0) ([raw file](https://github.com/stratumn/sdk/blob/149440e7564706a39dcb1874d3eb630955b2d5bd/store/event.go#L62)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: this could also receive template args like the constructor, it's more elegant (I should have done it from the start)
And maybe in that case the AddSaveLink above isn't necessary anymore
</blockquote></details>

True, I'll change it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/304)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/event.go, line 62 at r1](https://reviewable.io:443/reviews/stratumn/sdk/304#-L0j1aVjdnuDE2zz0p0O:-L0j7Pp7WP8SdDHk_Ayt:b-jwjjdc) ([raw file](https://github.com/stratumn/sdk/blob/149440e7564706a39dcb1874d3eb630955b2d5bd/store/event.go#L62)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

True, I'll change it
</blockquote></details>

Thanks! I think you might need to change it in tmpop.go otherwise it won't compile

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/304)*

**Comment by t-bast** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/event.go, line 62 at r1](https://reviewable.io:443/reviews/stratumn/sdk/304#-L0j1aVjdnuDE2zz0p0O:-L0jA98uGFHoElkR9sl0:bqq6gxq) ([raw file](https://github.com/stratumn/sdk/blob/149440e7564706a39dcb1874d3eb630955b2d5bd/store/event.go#L62)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Thanks! I think you might need to change it in tmpop.go otherwise it won't compile
</blockquote></details>

Ah no my bad, it's already good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/304#-:-L0jABA8m1R0TKYgHYLU:bnfp4nl)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/event.go, line 62 at r1](https://reviewable.io:443/reviews/stratumn/sdk/304#-L0j1aVjdnuDE2zz0p0O:-L0j9w6mbsfvwVvJ37OY:boy7min) ([raw file](https://github.com/stratumn/sdk/blob/149440e7564706a39dcb1874d3eb630955b2d5bd/store/event.go#L62)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Thanks! I think you might need to change it in tmpop.go otherwise it won't compile
</blockquote></details>

nop, In tmpop, it calls the function on the EventsManager which wants a slice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/304)*

**Pull request merged**
