### PR TITLE
Allow gotip build failures on Travis

### PR DESCRIPTION
**Pull request by alexppxela**
And do not wait for gotip build to validate PR

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/302)

### CODE REVIEW

**Comment by stephan83** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/302#-:-L0hqH_QblaSiKiX5E6R:bnfp4nl)*

**Comment by stephan83** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/302)*

**Comment by t-bast** [comment]
I'm not really sure it's worth having something that we allow failing on...
If we allow failures we won't investigate when it fails, so it's probably not even needed to run it and slow down our builds (because sometimes Travis doesn't run them in parallel when it's under load)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/302#-:-L0hrxrj7dhZ69ef2YVa:b-sd9i0l)*

**Comment by alexppxela** [comment]
I agree for build load, but it is interesting to know if our code is compliant with new go features.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/302#-:-L0htCPHHTJCwF9Phw_o:bjf5n8f)*

**Comment by such** [comment]
No strong opinion as well... Maybe the simpler, the better: only 1.9. I'm not expecting next go release to be painful.

**Comment by alexppxela** [comment]
To have faster build, we will keep only go 1.9.
Before go 2.0 release, it should be great to re-add tip to help code migration if needed

**Pull request closed without merging**
