### PR TITLE
cmd: cleanup fossilizers main commands

### PR DESCRIPTION
**Pull request by such**
- Use flags declared by fossilizerhttp
- Use context for signal handling

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/323)

### CODE REVIEW

**Comment by such** [comment]
I'm not an expert with `context` yet so any remark will be welcomed!

**Comment by stephan83** [comment]
*[utils/signalcontext.go, line 13 at r1](https://reviewable.io:443/reviews/stratumn/sdk/323#-L1waN_Eqsnma-RfSOqZ:-L1waN_FSFgNqpzkBiq-:b30cz85) ([raw file](https://github.com/stratumn/sdk/blob/7a5e1ddf6ed9fd7c495b3badf573a4fe90247f5a/utils/signalcontext.go#L13)):*
> ```Go
> 
> // CancelOnInterrupt creates a context and calls the context cancel function when an interrupt signal is caught
> func CancelOnInterrupt(ctx context.Context) context.Context {
> ```

That's cool, never thought of doing that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/323)*

**Comment by stephan83** [comment]
:lgtm:

Contexts are annoying, I hope they come up with a better alternative in Go 2.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/323#-:-L1wapKEbZEvrwxDTLEw:btmu3sp)*

**Comment by t-bast** [comment]
Reviewed 19 of 20 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[bcbatchfossilizer/util_test.go, line 50 at r2](https://reviewable.io:443/reviews/stratumn/sdk/323#-L1wcYTwQSmCYNR2LWvV:-L1wcYTx487CSZWr3wNK:b-w3bgj4) ([raw file](https://github.com/stratumn/sdk/blob/832a04f75215b3b66037a86a745f3288350f609b/bcbatchfossilizer/util_test.go#L50)):*
> ```Go
> 
> 	go func() {
> 		if err := a.Start(ctx); err != nil && errors.Cause(err) != context.Canceled {
> ```

Why do you need to add the check that error isn't because of cancellation?
In which case can you walk this code path with a cancelled context and have it still be ok?

---

*[blockchain/btc/btctimestamper/cmd.go, line 18 at r2](https://reviewable.io:443/reviews/stratumn/sdk/323#-L1wdtXG1lgr0k1ldpJv:-L1wdtXG1lgr0k1ldpJw:b-eqhmyn) ([raw file](https://github.com/stratumn/sdk/blob/832a04f75215b3b66037a86a745f3288350f609b/blockchain/btc/btctimestamper/cmd.go#L18)):*
> ```Go
> func RegisterFlags() {
> 	flag.Int64Var(&fee, "fee", DefaultFee, "transaction fee (satoshis)")
> ```

nit: empty line

---

*[utils/signalcontext.go, line 13 at r1](https://reviewable.io:443/reviews/stratumn/sdk/323#-L1waN_Eqsnma-RfSOqZ:-L1weF-cecXkHyJQHzj8:b-8fx2u7) ([raw file](https://github.com/stratumn/sdk/blob/7a5e1ddf6ed9fd7c495b3badf573a4fe90247f5a/utils/signalcontext.go#L13)):*
<details><summary><i>Previously, stephan83 (stephan) wrote…</i></summary><blockquote>

That's cool, never thought of doing that.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/323)*

**Comment by such** [comment]
Review status: 21 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[bcbatchfossilizer/util_test.go, line 50 at r2](https://reviewable.io:443/reviews/stratumn/sdk/323#-L1wcYTwQSmCYNR2LWvV:-L1wf4-63cEOadJzSDJW:bk67r80) ([raw file](https://github.com/stratumn/sdk/blob/832a04f75215b3b66037a86a745f3288350f609b/bcbatchfossilizer/util_test.go#L50)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Why do you need to add the check that error isn't because of cancellation?
In which case can you walk this code path with a cancelled context and have it still be ok?
</blockquote></details>

I don't want to error in case of a canceled context since I'm explicitly canceling it later in the test.

What might not be obvious here is that the call to `Start` is actually blocking. So the `context.Canceled` error is not thrown during actual startup but during the normal run of the adapter.

---

*[blockchain/btc/btctimestamper/cmd.go, line 18 at r2](https://reviewable.io:443/reviews/stratumn/sdk/323#-L1wdtXG1lgr0k1ldpJv:-L1wgAutyVC7aEqMHiyc:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/832a04f75215b3b66037a86a745f3288350f609b/blockchain/btc/btctimestamper/cmd.go#L18)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: empty line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/323)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bcbatchfossilizer/util_test.go, line 50 at r2](https://reviewable.io:443/reviews/stratumn/sdk/323#-L1wcYTwQSmCYNR2LWvV:-L1wkWLSUMjqReZ1AJKc:bypbv0) ([raw file](https://github.com/stratumn/sdk/blob/832a04f75215b3b66037a86a745f3288350f609b/bcbatchfossilizer/util_test.go#L50)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I don't want to error in case of a canceled context since I'm explicitly canceling it later in the test.

What might not be obvious here is that the call to `Start` is actually blocking. So the `context.Canceled` error is not thrown during actual startup but during the normal run of the adapter.
</blockquote></details>

Makes sense, thanks !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/323#-:-L1wkZhcOg7A_0EqxO4z:bnfp4nl)*

**Pull request merged**
