### PR TITLE
stores: remove old interface

### PR DESCRIPTION
**Pull request by t-bast**
Very satisfying to remove that much code :)
I have other clean-up to do, but that will be in another PR

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/282)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 61 of 61 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bufferedbatch/batch.go, line 39 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L03unVJKaI1ribGEN66:-L03unVJKaI1ribGEN67:bbbi91) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L39)):*
> ```Go
> // CreateLink implements github.com/stratumn/sdk/store.LinkWriter.CreateLink.
> func (b *Batch) CreateLink(link *cs.Link) (*types.Bytes32, error) {
> 	segment := link.Segmentify()
> ```

As previously discussed, will link validation stuff be moved on Link to do not create fake Segment in a next PR?

---

*[store/storetestcases/createlink.go, line 113 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L04-uU1mZixsljpEGdB:-L04-uU1mZixsljpEGdC:bcqgpz9) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/storetestcases/createlink.go#L113)):*
> ```Go
> 
> 	b.ResetTimer()
> 	log.SetOutput(ioutil.Discard)
> ```

Excellent for benchmarks!

---

*[store/storetestcases/deletevalue.go, line 26 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L040DKitgj2dgmhV1oE:-L040DKitgj2dgmhV1oF:b8v6cb5) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/storetestcases/deletevalue.go#L26)):*
> ```Go
> 
> 	"github.com/stratumn/sdk/testutil"
> 	"github.com/stretchr/testify/assert"
> ```

I prefer write tests using assert notation than go checks.
Is it ok for everyone to use _testify_ for all new tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bufferedbatch/batch.go, line 39 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L03unVJKaI1ribGEN66:-L043XqgSltGNUEo537r:b-ai35yv) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L39)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

As previously discussed, will link validation stuff be moved on Link to do not create fake Segment in a next PR?
</blockquote></details>

Yes, this will be for another PR otherwise it's too big :)

---

*[store/storetestcases/deletevalue.go, line 26 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L040DKitgj2dgmhV1oE:-L043eK3P-bS0OQpy9nd:bio2wbz) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/storetestcases/deletevalue.go#L26)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I prefer write tests using assert notation than go checks.
Is it ok for everyone to use _testify_ for all new tests?
</blockquote></details>

I recommend it, and when we discussed it with Adrien he preferred assertions as well.
So if everyone is ok, I think we should start using testify/assert everywhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by alexppxela** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bufferedbatch/batch.go, line 39 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L03unVJKaI1ribGEN66:-L0446Q056c0iVOF3zAh:b-j6u9bs) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L39)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Yes, this will be for another PR otherwise it's too big :)
</blockquote></details>

Perfect

---

*[store/storetestcases/deletevalue.go, line 26 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L040DKitgj2dgmhV1oE:-L044B6q8DQIFWxSidP5:b8sfiho) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/storetestcases/deletevalue.go#L26)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I recommend it, and when we discussed it with Adrien he preferred assertions as well.
So if everyone is ok, I think we should start using testify/assert everywhere
</blockquote></details>

For me, it is more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282#-:-L044IJ2yi1-0p6MG5z-:bnfp4nl)*

**Comment by piedup** [comment]
Reviewed 10 of 61 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[bufferedbatch/batch.go, line 40 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L040HylnSxuzzfFfPk0:-L040HylnSxuzzfFfPk1:briuyth) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L40)):*
> ```Go
> func (b *Batch) CreateLink(link *cs.Link) (*types.Bytes32, error) {
> 	segment := link.Segmentify()
> 	if err := segment.Validate(b.GetSegment); err != nil {
> ```

Are we moving the validation logic to the Link object?

---

*[bufferedbatch/batch.go, line 50 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L041DfRvTXArVPO8s_O:-L041DfSJanioiuCCkHh:b-nm60mp) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L50)):*
> ```Go
> func (b *Batch) GetSegment(linkHash *types.Bytes32) (segment *cs.Segment, err error) {
> 	for _, link := range b.Links {
> 		lh, err := link.Hash()
> ```

Would it be worth caching linkHashes in the batch object?

---

*[couchstore/batch.go, line 1 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L047CSqIlPBtL6_8h3J:-L047CSqIlPBtL6_8h3K:bd7chn5) ([raw file](https://github.com/stratumn/sdk/blob/9f6d60036a65a997a21ce5a3ec57548cd3530cc9/couchstore/batch.go#L1)):*
> ```Go
> // Copyright 2017 Stratumn SAS. All rights reserved.
> ```

This comment applies to all stores. Will we still have the ability to implement a specific batch rather than use bufferedBatch? We may want to save all links at once for some stores in the future rather than iterate over links.

---

*[store/storetestcases/addsavechannel.go, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L0484Kl_obfsdvIRuU7:-L0484Kl_obfsdvIRuU8:bn2bzq1) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/storetestcases/addsavechannel.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package storetestcases
> ```

Should we rename this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by piedup** [comment]
Reviewed 19 of 61 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bufferedbatch/batch.go, line 40 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L040HylnSxuzzfFfPk0:-L04ZfgTC8Yf7kkON2rT:boqatse) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L40)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Are we moving the validation logic to the Link object?
</blockquote></details>

It is scheduled for a next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bufferedbatch/batch.go, line 50 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L041DfRvTXArVPO8s_O:-L04bRtnnrmhCJyEgAte:b-ke0api) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L50)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Would it be worth caching linkHashes in the batch object?
</blockquote></details>

Maybe later if we see that it's a performance issue. No need to make the code more complex right now until it is an issue :)

---

*[couchstore/batch.go, line 1 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L047CSqIlPBtL6_8h3J:-L04bavfbz8gozuKKRKS:b8x83yt) ([raw file](https://github.com/stratumn/sdk/blob/9f6d60036a65a997a21ce5a3ec57548cd3530cc9/couchstore/batch.go#L1)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

This comment applies to all stores. Will we still have the ability to implement a specific batch rather than use bufferedBatch? We may want to save all links at once for some stores in the future rather than iterate over links.
</blockquote></details>

Yes you still can, it's just that for now almost none of the stores (except postgres and filestore) need more than what bufferedbatch does

---

*[store/storetestcases/addsavechannel.go, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L0484Kl_obfsdvIRuU7:-L04biWRHwb-tLRADz0-:b-f9vhms) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/storetestcases/addsavechannel.go#L15)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Should we rename this file?
</blockquote></details>

I'll do some more work in a later PR to split the test cases to match the new store interfaces, so it will be for later indeed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by such** [comment]
Reviewed 8 of 61 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[bufferedbatch/batch.go, line 50 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L041DfRvTXArVPO8s_O:-L04aNbqjckPEdYFP1aS:b-6nbgrn) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/bufferedbatch/batch.go#L50)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

Would it be worth caching linkHashes in the batch object?
</blockquote></details>

Good point, but this could be done in another PR

---

*[store/store.go, line 84 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L04cCLXBS3vm9aKBkNg:-L04cCLXBS3vm9aKBkNh:b76rra4) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/store.go#L84)):*
> ```Go
> 
> // Adapter is the minimal interface that all stores should implement.
> // Then a store may optionnally implement the KeyValueStore interface.
> ```

typo: optionally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by t-bast** [comment]
Review status: 59 of 60 files reviewed at latest revision, 5 unresolved discussions.

---

*[store/store.go, line 84 at r1](https://reviewable.io:443/reviews/stratumn/sdk/282#-L04cCLXBS3vm9aKBkNg:-L04dB5viqIcJi1vcvfg:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/210745b64258417616293943f01615d84faefe67/store/store.go#L84)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

typo: optionally
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Comment by piedup** [comment]
:lgtm:

---

Review status: 59 of 60 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282#-:-L04eTYGDLwyrdrYuBxR:bnfp4nl)*

**Comment by alexppxela** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/282)*

**Pull request merged**
