### PR TITLE
Cleanup Go Report issues

### PR DESCRIPTION
**Pull request by such**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/306)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[postgresstore/reader.go, line 90 at r1](https://reviewable.io:443/reviews/stratumn/sdk/306#-L0jIrpyGl0ZeVcqj4bI:-L0jIrpzv7LgEvsTiGP2:bauctmn) ([raw file](https://github.com/stratumn/sdk/blob/d13c4f28dfc0942816ec0ba32076cf22c749f135/postgresstore/reader.go#L90)):*
> ```Go
> 		linkHashes, err1 := cs.NewLinkHashesFromStrings(filter.LinkHashes)
> 		if err1 != nil {
> 			return nil, err
> ```

return nil, err1?
Why that change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/306)*

**Comment by such** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[postgresstore/reader.go, line 90 at r1](https://reviewable.io:443/reviews/stratumn/sdk/306#-L0jIrpyGl0ZeVcqj4bI:-L0jJhRNTXauGuZXkTzg:budqj23) ([raw file](https://github.com/stratumn/sdk/blob/d13c4f28dfc0942816ec0ba32076cf22c749f135/postgresstore/reader.go#L90)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

return nil, err1?
Why that change?
</blockquote></details>

Good catch!
This `err` was shadowing another `err` declared in the outer scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/306)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/306#-:-L0jJuH1M1kahnFtS6rz:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/306)*

**Comment by alexppxela** [comment]
:lgtm: 

---

Reviewed 5 of 8 files at r1, 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/stratumn/sdk/306#-L0jT-7Ox4P9KMk2qkV7:-L0jT-7Ox4P9KMk2qkV8:bs3vedg) (no related file):*
For information, where can we find the go report?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/306#-:-L0jSpdIzAUQ0duHTKNS:bg7igkv)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/stratumn/sdk/306#-L0jT-7Ox4P9KMk2qkV7:-L0jTCug3F25JNXrgy0z:b2twzzy) (no related file):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

For information, where can we find the go report?
</blockquote></details>

There's a badge on top of the README file. It links to https://goreportcard.com/report/github.com/stratumn/sdk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/306)*

**Comment by alexppxela** [comment]
*[a discussion](https://reviewable.io:443/reviews/stratumn/sdk/306#-L0jT-7Ox4P9KMk2qkV7:-L0n7VvkNOfsTNCY9DBR:b-erp7o6) (no related file):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

There's a badge on top of the README file. It links to https://goreportcard.com/report/github.com/stratumn/sdk.
</blockquote></details>

great. thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/306)*

**Pull request merged**
