### PR TITLE
Display the good binary version

### PR DESCRIPTION
**Pull request by alexppxela**
If compilation is on a tag, tag will be displayed, otherwise the branch
Now, it is not necessary anymore to update VERSION file.

### CODE REVIEW

**Comment by alexppxela** [comment]
This PR works when compiling a version but I realized that VERSION is also used to tag a new version. We need to speak about how to release sdk and I will adapt the PR.

**Comment by stephan83** [comment]
It seems a bit unconventional not to have the version somewhere in a file.

The problems I could see:

- It relies on git; without Git, for example if the code is downloaded as a Tarball, it makes the code version-less
- It's harder to know what version a branch corresponds to, and what version to bump to when making a release

Maybe we can compromise and have the binary output both the version in `VERSION` and the branch/tag (it already outputs the commit hash)?

**Comment by alexppxela** [comment]
I have never worked without SCM so I have not thought about sources download.
For the second point, it depends on your way of work. With a good shell extension, there is no matter to do not have a version file.
I have just checked on trending Go repositories and I have noted that a lot of Go repo contains a version file.

I think, it should be good idea to add the tag/branch when building a version to avoid incompatible modules in indigo just reading logs without checking commit hashes.

**Comment by such** [comment]
As a summary:
- We should add the tag/branch when building a version (like we do for the commit)
- We should get rid of the VERSION file on master and keep it only on release branches

**Comment by such** [comment]
@alexppxela @stephan83 I think this PR would be perfect if it took into account the VERSION file if present. Am I right?

**Comment by alexppxela** [comment]
Yes perfect to manage production branches

**Comment by alexppxela** [comment]
I'm just thinking about a problem because DefaultGeneratorsRef is GIT_TAG
`strat generate` will work on master and on version branches but will not work on other branches except if there is a generator version fallback to master.

**Comment by stephan83** [comment]
I think it's ok to pass the `--generators-ref=master` flag for these cases?

**Comment by alexppxela** [comment]
@stephan83 sorry I misread your comment and use generators master by default...
Do you prefer I delete the last commit?

**Comment by stephan83** [comment]
I think that works.

**Pull request merged**
