### PR TITLE
fossilizer: add websocket

### PR DESCRIPTION
**Pull request by bejito**
related to https://github.com/stratumn/sdk/issues/97:

- Add a websocket to the fossilizer
- Push an event in the websocket when data has been fossilized

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/274)

### CODE REVIEW

**Comment by bejito** [comment]
*[fossilizer/fossilizer.go, line 56 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-g1BujA3Uxddy7J4Ib:-L-g1BukpbuIU5RL46Kk:b-151ow4) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/fossilizer/fossilizer.go#L56)):*
> ```Go
> const (
> 	// DidFossilizeSegment means that segment was fossilized
> 	DidFossilizeSegment EventType = iota
> ```

I called it this way, but do we only fossilize segments ? Or are there other kind of entities that can be fossilized ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274#-:-L-g6qEm_xDcTCTw1r7d:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[batchfossilizer/batchfossilizer.go, line 151 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-gF6G0MBJ-qVLKt_9o:-L-gF6G0MBJ-qVLKt_9p:b-uf38wu) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/batchfossilizer/batchfossilizer.go#L151)):*
> ```Go
> 	batchChan            chan *batch
> 	stopChan             chan error
> 	semChan              chan struct{}
> ```

What does sem mean?
A more meaningful name would be useful.

---

*[batchfossilizer/batchfossilizer.go, line 416 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-gFJmATCRIK7aHOW1j:-L-gFJmATCRIK7aHOW1k:b6a0hp0) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/batchfossilizer/batchfossilizer.go#L416)):*
> ```Go
> 
> 			event := &fossilizer.Event{
> 				EventType: fossilizer.DidFossilizeSegment,
> ```

Maybe this should be renamed to DidFossilizeLink?
Because what we should be fossilizing are links, not segments right?

---

*[fossilizer/fossilizer.go, line 56 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-g1BujA3Uxddy7J4Ib:-L-gFh1zS3Y2ai6M8dvb:b5po66p) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/fossilizer/fossilizer.go#L56)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

I called it this way, but do we only fossilize segments ? Or are there other kind of entities that can be fossilized ?
</blockquote></details>

To be confirmed with Adrien, but I think that what we want to fossilize is the link (the immutable part).
Because the rest is:
  * link hash (computed from link)
  * evidences (which you don't want to fossilize because it's the fact that you fossilized that creates that evidence)

I would recommend to name this: "FossilizedLink" to be consistent with the store events

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
*[batchfossilizer/batchfossilizer.go, line 416 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-gFJmATCRIK7aHOW1j:-L-gI9Esaz-h6jbWsJbR:bmeyrwp) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/batchfossilizer/batchfossilizer.go#L416)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Maybe this should be renamed to DidFossilizeLink?
Because what we should be fossilizing are links, not segments right?
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
*[batchfossilizer/batchfossilizer.go, line 151 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-gF6G0MBJ-qVLKt_9o:-L-gOfU6CwQYy_Z41tly:b9js1pz) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/batchfossilizer/batchfossilizer.go#L151)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

What does sem mean?
A more meaningful name would be useful.
</blockquote></details>

I guess sem is for semaphore. It is used here to handle simultaneous batches

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
*[batchfossilizer/batchfossilizer.go, line 151 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-gF6G0MBJ-qVLKt_9o:-L-gRiT8nks2pSi9qI47:b-vw95up) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/batchfossilizer/batchfossilizer.go#L151)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

I guess sem is for semaphore. It is used here to handle simultaneous batches
</blockquote></details>

I'll add a comment next to it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
*[fossilizer/fossilizer.go, line 56 at r1](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-g1BujA3Uxddy7J4Ib:-L-gTPqKzlVOzp80_8lz:b-7rl0jr) ([raw file](https://github.com/stratumn/sdk/blob/9066b46cccf2a4d2e6d10d3f4c48a6c0411bddc1/fossilizer/fossilizer.go#L56)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

To be confirmed with Adrien, but I think that what we want to fossilize is the link (the immutable part).
Because the rest is:
  * link hash (computed from link)
  * evidences (which you don't want to fossilize because it's the fact that you fossilized that creates that evidence)

I would recommend to name this: "FossilizedLink" to be consistent with the store events
</blockquote></details>

done 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
Okay, I was not sure if this callback was used for something else. 
@such I guess we do not care about retro compatibility at this point ?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274#-:-L-gXxQUfU0WnPn9iqHv:b-1mcu9u)*

**Comment by alexppxela** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by t-bast** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[fossilizer/fossilizer.go, line 59 at r2](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-ggqOQxQgrGOliQfNW:-L-ggqOQxQgrGOliQfNX:b-4msyho) ([raw file](https://github.com/stratumn/sdk/blob/5b1a77a585c17a598ae9ae6910d071fb0c07fd79/fossilizer/fossilizer.go#L59)):*
> ```Go
> )
> 
> // Event is the object stores send to notify of important events.
> ```

nit: wrong copy-paste, it's a fossilizer, not a store :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
*[fossilizer/fossilizer.go, line 59 at r2](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-ggqOQxQgrGOliQfNW:-L-ghZO-xMYnN5W_c4BE:ba73nnq) ([raw file](https://github.com/stratumn/sdk/blob/5b1a77a585c17a598ae9ae6910d071fb0c07fd79/fossilizer/fossilizer.go#L59)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: wrong copy-paste, it's a fossilizer, not a store :)
</blockquote></details>

hehe indeed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by t-bast** [comment]
Reviewed 1 of 2 files at r3, 17 of 17 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[batchfossilizer/batchfossilizer.go, line 406 at r4](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-lkCiIz4_2cesa2Qrw:-L-lkCiIz4_2cesa2Qrx:b-b42sue) ([raw file](https://github.com/stratumn/sdk/blob/7422976ecdb805c1392ef2b5cf1ed07dbb32541e/batchfossilizer/batchfossilizer.go#L406)):*
> ```Go
> 			event := &fossilizer.Event{
> 				EventType: fossilizer.DidFossilizeLink,
> 				Details:   r,
> ```

nit: to align with msg and the store event, you could rename this "Data"

---

*[fossilizer/fossilizer.go, line 49 at r4](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-lm_XVd3AvGHk4AirN:-L-lm_XVd3AvGHk4AirO:buzqblm) ([raw file](https://github.com/stratumn/sdk/blob/7422976ecdb805c1392ef2b5cf1ed07dbb32541e/fossilizer/fossilizer.go#L49)):*
> ```Go
> // EventType lets you know the kind of event received.
> // A client should ignore events it doesn't care about or doesn't understand.
> type EventType int
> ```

in store, I changed that to be a string so that it's easier to convert to the msg event type (and easier to debug)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
*[fossilizer/fossilizer.go, line 49 at r4](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-lm_XVd3AvGHk4AirN:-L-lpDOsbrFahlDOhVHr:bnwc2mt) ([raw file](https://github.com/stratumn/sdk/blob/7422976ecdb805c1392ef2b5cf1ed07dbb32541e/fossilizer/fossilizer.go#L49)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

in store, I changed that to be a string so that it's easier to convert to the msg event type (and easier to debug)
</blockquote></details>

hm, I think you are mixing this up with the actual message sent in the websocket.
https://github.com/stratumn/sdk/blob/master/store/store.go#L149

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
*[batchfossilizer/batchfossilizer.go, line 406 at r4](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-lkCiIz4_2cesa2Qrw:-L-lpPmnb7Ii5ph21BUN:b3f10w5) ([raw file](https://github.com/stratumn/sdk/blob/7422976ecdb805c1392ef2b5cf1ed07dbb32541e/batchfossilizer/batchfossilizer.go#L406)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: to align with msg and the store event, you could rename this "Data"
</blockquote></details>

actually, in the store too the event looks like this, and is then wrapped in a Message that actually has a Data and a string Type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[batchfossilizer/batchfossilizer.go, line 406 at r4](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-lkCiIz4_2cesa2Qrw:-L-lqik53kkni-CE9M6a:b-4enm1m) ([raw file](https://github.com/stratumn/sdk/blob/7422976ecdb805c1392ef2b5cf1ed07dbb32541e/batchfossilizer/batchfossilizer.go#L406)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

actually, in the store too the event looks like this, and is then wrapped in a Message that actually has a Data and a string Type
</blockquote></details>

I'm changing that (the PR is not sent yet) :)

---

*[fossilizer/fossilizer.go, line 49 at r4](https://reviewable.io:443/reviews/stratumn/sdk/274#-L-lm_XVd3AvGHk4AirN:-L-lqnj8jd20CbOeVKAn:bfjgr3w) ([raw file](https://github.com/stratumn/sdk/blob/7422976ecdb805c1392ef2b5cf1ed07dbb32541e/fossilizer/fossilizer.go#L49)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

hm, I think you are mixing this up with the actual message sent in the websocket.
https://github.com/stratumn/sdk/blob/master/store/store.go#L149
</blockquote></details>

No I'm changing that (PR incoming)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by t-bast** [comment]
:lgtm: but probably needs someone with some knowledge of the fossilizers / websockets to have a look

---

Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274#-:-L-m-aLiu7E3lnXjQbRg:b-f1q8hz)*

**Comment by such** [comment]
Reviewed 2 of 14 files at r1, 1 of 2 files at r3, 9 of 17 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[fossilizer/fossilizer.go, line 27 at r5](https://reviewable.io:443/reviews/stratumn/sdk/274#-L04ZkRawtwGj_wAMtAE:-L04ZkRawtwGj_wAMtAF:bf2iyrg) ([raw file](https://github.com/stratumn/sdk/blob/39e1b3326c7480975c6ce988303e466ccfb75373/fossilizer/fossilizer.go#L27)):*
> ```Go
> 	GetInfo() (interface{}, error)
> 
> 	// Adds a channel that receives revents from the fossilizer
> ```

typo: revents

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by bejito** [comment]
Review status: 17 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[fossilizer/fossilizer.go, line 27 at r5](https://reviewable.io:443/reviews/stratumn/sdk/274#-L04ZkRawtwGj_wAMtAE:-L04jL0oPcNsAKQqyzzC:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/39e1b3326c7480975c6ce988303e466ccfb75373/fossilizer/fossilizer.go#L27)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

typo: revents
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274#-:-L04vlwxWzr-uKQjPynp:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/274)*

**Pull request merged**
