### PR TITLE
release: update CHANGELOG

### PR DESCRIPTION
**Pull request by alexppxela**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/229)

### CODE REVIEW

**Comment by t-bast** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGE_LOG.md, line 20 at r1](https://reviewable.io:443/reviews/stratumn/sdk/229#-KyRY5huFfKNEy1DvPgn:-KyRY5huFfKNEy1DvPgo:b-80asa6) ([raw file](https://github.com/stratumn/sdk/blob/6b0f6a151d8b9928d5d62be4066943995e8f6dbc/CHANGE_LOG.md#L20)):*
> ```Markdown
> * Cleaned up command flags.
> * Cleaned logs
> ```

very nit: the usage of a '.' at the end of the line/sentence isn't very consistent, I'd recommend putting a '.' at the end of each sentence

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/229)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/229#-:-KyRYp1r4hy3NJdFEdk7:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/229)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[CHANGE_LOG.md, line 20 at r1](https://reviewable.io:443/reviews/stratumn/sdk/229#-KyRY5huFfKNEy1DvPgn:-KyV4dRHI49alpfZwKXG:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/6b0f6a151d8b9928d5d62be4066943995e8f6dbc/CHANGE_LOG.md#L20)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

very nit: the usage of a '.' at the end of the line/sentence isn't very consistent, I'd recommend putting a '.' at the end of each sentence
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/229)*

**Comment by such** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/229)*

**Pull request merged**
