### PR TITLE
tendermint: update to 0.13.0

### PR DESCRIPTION
**Pull request by t-bast**
Update to Tendermint 0.13.0 (0.14.0 is advertised as release but in fact it requires a commit from tmlibs' develop branch, so it's not really ready for release yet).
There was a big types change where Tendermint removed a lot of their types and forces us to have different return types per ABCI operation. I think it's overall a good change, our internal types in TMPoP were too tightly coupled with Tendermint's types, so I introduced an ABCIError type inside TMPoP.
Socket management / events changed a lot and isn't well documented, I had to dig through Tendermint's code to get it to work.
I want to do an end-to-end test with multiple nodes before committing this change, I'll be working on that today and will report the results on this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/292)

### CODE REVIEW

**Comment by bejito** [comment]
*[tmpop/error.go, line 29 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0EdFkEN7K5hp5E2SR_:-L0EdFkEN7K5hp5E2SRa:b-6fduku) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/error.go#L29)):*
> ```Go
> 
> 	// CodeTypeNotImplemented is the ABCI error code for a feature not yet implemented.
> 	CodeTypeNotImplemented uint32 = 501
> ```

So they expose CodeTypeOK but not the error code types ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292)*

**Comment by bejito** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292)*

**Comment by such** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tmpop/tmpop.go, line 158 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0Eg3mvijFjJUb7QOi1:-L0Eg3mvijFjJUb7QOi2:bx56zmw) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/tmpop.go#L158)):*
> ```Go
> 	if t.currentHeader == nil {
> 		log.Error("Cannot begin block without header")
> 		return abci.ResponseBeginBlock{}
> ```

We could return the error as a message in the response. I'm not sure it's how it's supposed to be used though...

---

*[tmstore/tmstore.go, line 121 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0EgtA_GBqRFF9sFQ2-:-L0EgtA_GBqRFF9sFQ20:bnpg7ut) ([raw file](https://github.com/stratumn/sdk/blob/3164b76d2e354feba729dabbdd7e2a9449743486/tmstore/tmstore.go#L121)):*
> ```Go
> 			// we have to recreate the client in case of errors
> 			// (Check if it is still needed on Tendermint updates)
> 			t.tmClient = t.clientFactory(t.config.Endpoint)
> ```

If you can actually delete that (and it would be great!), I think you can simplify the "constructor" since the whole clientFactory is not needed anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292)*

**Comment by alexppxela** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tmpop/error.go, line 34 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0Egj6A9QQ4v09fG1Sw:-L0Egj6A9QQ4v09fG1Sx:bjmkdh0) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/error.go#L34)):*
> ```Go
> // ABCIError is a structured error used inside TMPoP.
> // The error codes are close to standard http status codes.
> type ABCIError struct {
> ```

Why `ABCIError` doest not implement error interface? You can benefit of the nil statement and `pkg.errors` is necessary

---

*[tmpop/tmpoptestcases/transaction.go, line 88 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0Ej3daDEeFdQ6PNdvU:-L0Ej3daDEeFdQ6PNdvV:bvqo0uh) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/tmpoptestcases/transaction.go#L88)):*
> ```Go
> 		link, tx := makeCreateRandomLinkTx(t)
> 		linkHash, _ := link.Hash()
> 		h.CheckTx(tx)
> ```

Is there an interest to check returned value of CheckTx?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tmpop/error.go, line 29 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0EdFkEN7K5hp5E2SR_:-L0F-AwuG8e6gACJDa1C:b-mam2yl) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/error.go#L29)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

So they expose CodeTypeOK but not the error code types ?
</blockquote></details>

Exactly, it's the only code they expose. I think it makes sense, Tendermint shouldn't care about the details of the errors we generate so we should be responsible for defining our error codes 

---

*[tmpop/error.go, line 34 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0Egj6A9QQ4v09fG1Sw:-L0F-NG0RIhy7XfKDkUH:bqpv8t5) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/error.go#L34)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why `ABCIError` doest not implement error interface? You can benefit of the nil statement and `pkg.errors` is necessary
</blockquote></details>

Cool, I'm simply new to error handling in Go. It probably makes sense to do what you propose, I'll dig into it.

---

*[tmpop/tmpop.go, line 158 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0Eg3mvijFjJUb7QOi1:-L0F-bcJPEEDFfu3Y6wC:b-tvslaw) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/tmpop.go#L158)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

We could return the error as a message in the response. I'm not sure it's how it's supposed to be used though...
</blockquote></details>

abci.ResponseBeginBlock is currently an empty struct, so Tendermint probably doesn't support us returning an error in there yet.
But the fact that they created a dedicated type indicates that at some time in the future they probably will allow us to put interesting data in there.

---

*[tmpop/tmpoptestcases/transaction.go, line 88 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0Ej3daDEeFdQ6PNdvU:-L0F-pbxwGAt68oD2Wfv:b8qg902) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/tmpoptestcases/transaction.go#L88)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Is there an interest to check returned value of CheckTx?
</blockquote></details>

Not in this test, because this is supposed to test DeliverTx

---

*[tmstore/tmstore.go, line 121 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0EgtA_GBqRFF9sFQ2-:-L0F-xXgv2xSLvjp2piF:bg9rbnt) ([raw file](https://github.com/stratumn/sdk/blob/3164b76d2e354feba729dabbdd7e2a9449743486/tmstore/tmstore.go#L121)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

If you can actually delete that (and it would be great!), I think you can simplify the "constructor" since the whole clientFactory is not needed anymore.
</blockquote></details>

Good point, I'll need to dig into this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292)*

**Comment by t-bast** [comment]
Actually there is an issue in the pubsub channel when running against a real Tendermint node over a websocket and that isn't caught by the tests (it's probably because of serialization / deserialization).
I need to fix that, so please hold off your reviews until this is fixed :)

---

Review status: 12 of 19 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292#-:-L0FGXFT_M1nc-_vhfek:b-bf5sbw)*

**Comment by such** [comment]
Reviewed 1 of 18 files at r1, 4 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tmpop/tmpoptestcases/transaction.go, line 88 at r1](https://reviewable.io:443/reviews/stratumn/sdk/292#-L0Ej3daDEeFdQ6PNdvU:-L0FiKJ-8Jd7UQdE2wPV:bff2qsj) ([raw file](https://github.com/stratumn/sdk/blob/ddc3a9baa71d92a363431c563d239661da7819ff/tmpop/tmpoptestcases/transaction.go#L88)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Not in this test, because this is supposed to test DeliverTx
</blockquote></details>

Excuse, you're true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292#-:-L0Fis_QLXgTvaUuVLEc:bnfp4nl)*

**Comment by t-bast** [comment]
The code changes are probably good, but it looks like there might be a serialization bug in Tendermint 0.13.0: https://github.com/tendermint/tendermint/issues/971
I'm holding off this PR until I get an answer from the Tendermint team or can figure out if I'm the one messing things up :)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292#-:-L0FnUuK0Oah5GkZVeBi:b-ngkqef)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292#-:-L0db3AcyBw8shDR5yjE:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292#-:-L0dcmca4XR8rCDxQj3T:bnfp4nl)*

**Comment by bejito** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/292#-:-L0eGoEdNNJCiXcTJskO:bnfp4nl)*

**Pull request merged**
