### PR TITLE
dummystore: migrate to new interface

### PR DESCRIPTION
**Pull request by t-bast**
This one was pretty simple.
Migrate the dummy store to implement the new store interface and run both test suites.
I think that after that, it's time to migrate the "big stores" (like postgres, couch and rethink). The initial implementers of these stores will most likely do it a lot faster than me, so if I could get help on that it would be perfect !

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/251)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[dummystore/dummystore.go, line 65 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi2sc3UE-7yIoAkmAt:-Kzi2sc3UE-7yIoAkmAu:b-ujoryy) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/dummystore/dummystore.go#L65)):*
> ```Go
> 	values       valueMap     // maps keys to values
> 	maps         hashSetMap   // maps chains IDs to sets of link hashes
> 	mutex        sync.RWMutex // simple global mutex
> ```

It seems that recursive mutex is not necessary.
Mutex is locked in public functions only. And private functions call only private functions.

---

*[dummystore/dummystore.go, line 225 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi1VTrFgYej3W6npj_:-Kzi1VTrFgYej3W6npja:btpwa7f) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/dummystore/dummystore.go#L225)):*
> ```Go
> 	linkHashStr := linkHash.String()
> 	segment, err := a.getSegment(linkHashStr)
> 	if err != nil {
> ```

Should be
if err != nil || segment == nil {
	return nil, err
}

---

*[store/store.go, line 331 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi4jonEkOofLId-8d4:-Kzi4jonEkOofLId-8d5:bs6ng1w) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/store/store.go#L331)):*
> ```Go
> 
> // Match checks if segment matches with filter
> func (filter MapFilter) Match(segment *cs.Segment) bool {
> ```

Should call MatchLink. But this method will be removed later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/251)*

**Comment by alexppxela** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/251)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[dummystore/dummystore.go, line 65 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi2sc3UE-7yIoAkmAt:-Kzi9HAcIqU-nshA1vBI:b64jlzt) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/dummystore/dummystore.go#L65)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

It seems that recursive mutex is not necessary.
Mutex is locked in public functions only. And private functions call only private functions.
</blockquote></details>

Good point. But does that mean we have a potential bug because we forget to do a read lock when we're reading ? Or does that mean we can simplify with a simple mutex ? I'll have to test this :)

---

*[dummystore/dummystore.go, line 225 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi1VTrFgYej3W6npj_:-Kzi9Xs6yGatPmKAChv8:b-hay2j5) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/dummystore/dummystore.go#L225)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Should be
if err != nil || segment == nil {
	return nil, err
}

</blockquote></details>

Thanks !

---

*[store/store.go, line 331 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi4jonEkOofLId-8d4:-Kzi9sD3YdxlcEAhaQgQ:b-hay2j5) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/store/store.go#L331)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Should call MatchLink. But this method will be removed later.
</blockquote></details>

Thanks !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/251)*

**Comment by t-bast** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[dummystore/dummystore.go, line 65 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi2sc3UE-7yIoAkmAt:-KziAzamSCvWVeQXTN9W:bbuvmt1) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/dummystore/dummystore.go#L65)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Good point. But does that mean we have a potential bug because we forget to do a read lock when we're reading ? Or does that mean we can simplify with a simple mutex ? I'll have to test this :)
</blockquote></details>

In fact we correctly use a read/write lock, I just forgot to read lock in GetEvidences

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/251)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/251#-:-KziC-fx8tVU2xnnuksm:bnfp4nl)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dummystore/dummystore.go, line 65 at r1](https://reviewable.io:443/reviews/stratumn/sdk/251#-Kzi2sc3UE-7yIoAkmAt:-KziAEL9hZXyIQoXh3wP:buf4hgq) ([raw file](https://github.com/stratumn/sdk/blob/b933f6c62843558e99991e864e7ba98c7f1eb25e/dummystore/dummystore.go#L65)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Good point. But does that mean we have a potential bug because we forget to do a read lock when we're reading ? Or does that mean we can simplify with a simple mutex ? I'll have to test this :)
</blockquote></details>

Sorry I've read too fast... It is not a RecursiveLock but a ReadWriteLock...
Please forget my previous comment ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/251)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/251#-:-KziCHzkjBTpGav2L7OC:bnfp4nl)*

**Pull request merged**
